### ISSUE TITLE
Grouping of Task in Context Menu by Plugin

### ISSUE THREAD

**Issue by mam0nth** [kelemen/netbeans-gradle-project#104]
When you right click in project node there is a "Task" in context showing all the available task. Having a more plugin it is hard to find the task you want to be executed. Currently the task was sort alphabetically. It is good to have if it is group by plugin and sorted alphabetically. So it can easy to find the task.

**Comment by kelemen** [comment]
This should now be fixed in master. Tasks are grouped automatically by their name, if there are too many (currently this limit is hardcoded to 20). For example: "compileJava" and "compileGroovy" should be in a menu "compile" (assuming there are more than 20 tasks).
