### ISSUE TITLE
Extra sourceDirs not showing up in editor

### ISSUE THREAD

**Issue by jeffreyguenther** [kelemen/netbeans-gradle-project#115]
I'm using: 

Product Version: NetBeans IDE 7.4 (Build 201310111528)
Updates: NetBeans IDE is updated to version NetBeans 7.4 Patch 2
Java: 1.7.0_51; Java HotSpot(TM) 64-Bit Server VM 24.51-b03
Runtime: Java(TM) SE Runtime Environment 1.7.0_51-b13
System: Mac OS X version 10.9.1 running on x86_64; UTF-8; en_US (nb)

The netbeans gradle plugin version is: Version: 1.2.9

I run the build file found here https://github.com/jrguenther/shiro/blob/master/build.gradle and the generated sources are not added to the netbeans project. As a result netbeans gives compiler errors. The odd things is one I was able to get the generated files to show up in the editor, but I can't remember how. My understanding is the idea plugin reference should take care of this for me.

```
idea {
    module {
        sourceDirs += file('src/generated-sources/java')
    }
}
```

Can you help?

**Comment by Tarrasch** [comment]
For friends on the interwebz who use `net.ltgt.apt` as is recommended for auto-value and Dagger2. You can add this to `build.gradle`:

```
if (project.hasProperty('evaluatingIDE') && project.property('evaluatingIDE') == 'NetBeans') {
  sourceSets.main.java.srcDir file('build/generated/source/apt/main/')
}
```

Then rightclick  and select Reload on your Gradle project in Netbeans. After that, I still needed to remove the cache (close NetBeans and nuke `$HOME/.cache/netbeans/8.1`):

![selection_037](https://cloud.githubusercontent.com/assets/294349/17732740/78f68332-649d-11e6-94fb-1e3b277e2c98.png)
