### ISSUE TITLE
Add Ability to customise name

### ISSUE THREAD

**Issue by leesdolphin** [kelemen/netbeans-gradle-project#117]
It would be really nice if you could provide a way of customising the name displayed in the IDE; even with just pre-sets such as 'project.name', 'project.path', 'project.group:project.name'

Thanks

**Comment by kelemen** [comment]
The project name is now customizable the same way as it is done in Maven projects. However, I cannot push to Github at the moment, so the changes are not yet uploaded. If you think there should be other ways to customize the name, feel free to recommend new pattern variables.
