### ISSUE TITLE
How to pass cli args to ext.mainClass in NB using G4NB?

### ISSUE THREAD

**Issue by fwelland** [kelemen/netbeans-gradle-project#124]
Hi, 

I have a standalone program that I am working on.  Short of hacking a String args[] array in main, is there a simple way to pass CLI args to the program so that "f6" (or debug) works?  

(In a fashion similar to the "Run" preferences of a native NB java application project)

Thanks!

**Comment by jdevora** [comment]
The same way that the -PmainClass=${selected-class}  gets passed to gradle and picked up by the run task.
There should be a special property (e.g. mainClassArgs)  that if present should be used the same way we use the 'args' property in the JavaExec task...

**Comment by kelemen** [comment]
See #194. Also, I'm closing this as a duplicate of #194.
