### ISSUE TITLE
Compilation fails only in IDE for srcDirs not within project directory

### ISSUE THREAD

**Issue by shevek** [kelemen/netbeans-gradle-project#130]
I have a multi-module project. If I set up a srcDir which is not within the project, NetBeans can't compile the files, but gradle can. Here is a rough skeleton:

project(':foo') {
  dependencies { compile project(':bar') }

// The default src/main/java works fine.

// This works fine
sourceSets.main.java.srcDir file('src/main/template')

// Any files in here don't get project 'bar' on the classpath.
sourceSets.main.java.srcDir rootProject.file('tmp/src')

// Neither do these:
sourceSets.main.java.srcDir file('../tmp/src')
}

They appear in the IDE fine, but they don't compile in the IDE - but commandline gradle CAN compile them.

If I symlink the out-of-project dir into the project, it works fine. The IDE even resolves (expands) the symlink and displays the absolute path.

**Comment by kelemen** [comment]
This should be fixed in master (reopen if anyone still experiences this issue).

**Comment by kelemen** [comment]
Accidentally closed the wrong issue.

**Comment by kelemen** [comment]
Should now be fixed in master.
