### ISSUE TITLE
NetBeans does not show packages or classes for secondary source directories in build/

### ISSUE THREAD

**Issue by shevek** [kelemen/netbeans-gradle-project#132]
I have lots of generated sources in build/generated-sources/[...]. Netbeans cannot show the packages or sources in these build/* directories, although they do work in the src/* directories.

Examples of plugins which generate these build/generated-sources directories include gradle-velocity-plugin, gradle-sablecc-plugin, gradle-jaxb-plugin, and so forth.

This may be related to https://github.com/kelemen/netbeans-gradle-project/issues/130 but I've raised it separately, as it's quite a distinct bug: The sources aren't shared, and they are within the project root.

**Comment by kelemen** [comment]
This should be fixed in master (reopen if anyone still experiences this issue).
