### ISSUE TITLE
Issue resolving dependencies through a proxy

### ISSUE THREAD

**Issue by imartinbe** [kelemen/netbeans-gradle-project#139]
Plugin : 1.3.0, Netbeans 7.4 & 8.0, gradle 1.11
I am busy setting my project to download dependencies from maven repositories.
I have the following setting in my build.gradle : 

```
repositories {
        maven {
            url "http://repo.jfrog.org/artifactory/repo1-cache"            
        }
        maven {
           url "http://repo.jfrog.org/artifactory/jcenter-cache"            
        }
}
```

I have also set the proxy configuration in **_%GRADLE_USER_HOME%\gradle.properties**_ file : 

```
systemProp.http.proxyUser=myUser
systemProp.http.proxyPassword=mySecret
systemProp.http.proxyHost=proxy.intranet
systemProp.http.proxyPort=8080
systemProp.http.nonProxyHosts=*.intranet|localhost
systemProp.https.proxyUser=myUser
systemProp.https.proxyPassword=mySecret
systemProp.https.proxyHost=proxy.intranet
systemProp.https.proxyPort=8080
systemProp.https.nonProxyHosts=*.intranet|localhost
```

I have some dependencies set in the project : 

```
compile group: 'junit', name: 'junit', version: '4.10'
```

When I launch a **_gradle clean build**_ or **_reload project**_ or any other task in Netbeans project, it hangs for a while and then I get this stacktrace in the notifications : 

```
Caused by: org.netbeans.gradle.model.util.TransferableExceptionWrapper: org.gradle.api.internal.externalresource.transport.http.HttpRequestException: Could not HEAD 'http://repo.jfrog.org/artifactory/repo1-cache/junit/junit/4.10/junit-4.10.jar'.
...
Caused by: org.netbeans.gradle.model.util.TransferableExceptionWrapper: java.net.SocketException: Malformed reply from SOCKS server
```

If I launch **_gradle clean build**_ on command line (from git bash), it downloads correctly the dependencies.
My GRADLE_USER_HOME environment variable is set the same way as in the plugin options.

```
Download http://repo.jfrog.org/artifactory/repo1-cache/junit/junit/4.10/junit-4.10.jar
```

I wonder if the netbeans plugin is taking the correct proxy settings (from gradle.properties)

**Comment by kelemen** [comment]
I have found a workaround for this issue:

Create an "init.gradle" in "~/.gradle" and add the following code to it:

    System.properties.remove('socksProxyHost')
    System.properties.remove('socksProxyPort')

The problem is that NetBeans adds these properties as well and Apache's `SystemDefaultHttpClient` will ignore the non proxy list when the above properties are present.

Sadly, I don't think this solves #146 because the Gradle dist gets downloaded before scripts are executed (for obvious reasons). In that case, you have to disable the proxy in NetBeans for the first run (and may re-enable later).

**Comment by kelemen** [comment]
Added workaround to automatically apply the following code through init scripts:

    System.properties.remove('socksProxyHost')
    System.properties.remove('socksProxyPort')

That is, you no longer need to add these lines manually.
