### ISSUE TITLE
Error loading project with sub-projects

### ISSUE THREAD

**Issue by corneil** [kelemen/netbeans-gradle-project#143]
We have a project with sub-projects.
Opening one of the sub-projects within NetBeans causes an error that indicates the gradle.properties from the root project was not loaded. 
This happens on command-line if gradle is executed in that folder without -p or -c option.
If I use IntelliJ IDEA or Eclipse with Gradle plugin the same project and sub-projects are imported without any issues.
It seems the solution would be to provide -p to gradle with location of root project. 
I cannot find a way to pass common options to gradle.

**Comment by aplatypus** [comment]
Hello.  I'd like to pass a comment on this point.  The Maven support in Netbeans honours the basic POM structure of project, sub-project, sub-subproject, etc.  

The limitation is therefore not in Netbeans per se, it is simply frustrated by the olde netbeans project model.  It is a much better solution to make a Gradle project model that models the Gradle model in a similar fashion to the Maven project model used with the Maven support.  

As a first step though, I believe the Gradle support would operate more _nicer_ by using the same project model the Netbeans Maven support uses.

**Comment by kelemen** [comment]
> As a first step though, I believe the Gradle support would operate more nicer by using the same project model the Netbeans Maven support uses.

I don't understand your comment. This issue does not even makes sense in the context of Maven. By the way, I think this issue should be fixed the best way I think it is possible. Though if anyone has any idea how to improve the current behaviour, I'm open to any idea.
