### ISSUE TITLE
Duplicate 'Source' tab in editor

### ISSUE THREAD

**Issue by JWahle** [kelemen/netbeans-gradle-project#147]
The tabs in the editor are Source, Source and History.
I think, source should only be there once.
![duplicate source tab](https://cloud.githubusercontent.com/assets/7657699/3607088/bcce1e36-0d41-11e4-8b33-b10a7f199c9d.png)

**Comment by kelemen** [comment]
This was fixed a long time ago, just forgot about the issue.
