### ISSUE TITLE
"Platform for build scripts" can't be selected properly when a Remote Java SE platform is added

### ISSUE THREAD

**Issue by swpalmer** [kelemen/netbeans-gradle-project#151]
I was following instructions at https://netbeans.org/kb/docs/java/javase-embedded.html to configure NB for developing remotely for Raspberry PI.  I added a new remote JDK called "RaspberryPI"

I do not think that the Gradle plugin supports this, but that is not the issue.

After configuring a remote platform as well as having the standard local JDK I encountered an issue with my Gradle projects.  In the project Properties on the "Gradle project" page there is a field for "Platform for build scripts"  This field was set to my remote JDK on the Raspberry PI.  I could not select the local JDK 1.8 - in fact it seems that it considered both of those options to be the same! There were two options in the combobox drop-down, both checked. One for JDK 1.8 and one for RaspberryPI.  Selecting JDK 1.8 (default) would just show RaspberryPI as the selection.  When I added another JDK (1.7) then I would see three selections and I was able to pick JDK 1.7.  But whenever I picked either of RaspberryPI or JDK 1.8, both of those would be checked and RaspberryPI would show as selected.

In this state the IDE claims:

cannot access java.lang
  Fatal Error: Unable to find package java.lang in classpath or bootclasspath
----
(Alt-Enter shows hints)

and it marks all the source files as having errors.  The Grade build still works though.

It seems having a remote JDK configured confuses things for Gradle projects.

**Comment by kelemen** [comment]
This should now be fixed in master. The platforms can now be ordered in the global settings (also, there is a button to show this dialog in the project properties). That is, the order of the platforms will decide which platform to choose when they have the same version.
