### ISSUE TITLE
classpath on new project

### ISSUE THREAD

**Issue by xenoterracide** [kelemen/netbeans-gradle-project#155]
so after creating a new project using new gradle project in netbeans, and the code builds and runs... but netbeans shows code errors due to missing dependencies  in the classpath. I've read the readme but was unable to get the `idea { .. }` block to work. What I don't understand is if that's necessary for netbeans to work correctly with gradle, why isn't it in the generated code. I'm apparently not familiar enough with gradle or netbeans to fix this problem.

this bug is for "new projects should have all the things they need to work"

**Comment by JustGregory** [comment]
Also a slight hint on having project dependencies errors, I'm in the practice of after creating a new Gradle project, of opening the command prompt at the project directory and running a gradlew.bat clean and build; that has always seemed to preemptively "straighten out" any future dependency links necessary. Also, as a project grows, I'm doing the same process, just to keep things cleaned, built, and as streamlined as possible.

(It may not be strictly "necessary" to do, but, eh, "it works for me".)
