### ISSUE TITLE
Can't run class form test sources

### ISSUE THREAD

**Issue by amariottini** [kelemen/netbeans-gradle-project#161]
Previously I used Ant and I have a lot of main in the test classes.
The purpose is to quickly execute some code as: show a window and see the layout, call a url to download some file from external services, produce a file with some defined content etc....
This is code I don't want to be packaged in the final jar.
With a project based on Ant it was possible but not with the Gradle plugin: it can't find the class, I think the class path is not properly set.

**Comment by amariottini** [comment]
I have this error:
......
Caused by: org.gradle.api.InvalidUserDataException: Cannot add task ':run' as a task with that name already exists.

**Comment by kelemen** [comment]
Replace `createJavaExec('run')` with

    run.main = definedMainClass
     // The next line is probably not needed if you already have a run task.
    run.classpath = project.sourceSets.test.runtimeClasspath
    run.standardInput = System.in

I guess, that you are using the application plugin which already adds a run task.

**Comment by amariottini** [comment]
Perfect!
Thanks.
