### ISSUE TITLE
Imports from subprojects do not work in the editor

### ISSUE THREAD

**Issue by f-stoffel** [kelemen/netbeans-gradle-project#170]
Using the current version of NetbBeans and the Gradle Support plugin, importing classes from subprojects does not work in the NetBeans editor. After adding the import statement manually, the code compiles fine - but the editor error regarding an unknown symbol is still displayed.

## Platform

Java: 1.8.0_25
Netbeans: NetBeans IDE 8.0.2 (Build 201411181905)
Gradle Plugin: Gradle Support 1.3.2 (installed via plugin manager)

## Steps to reproduce

* Create a new Gradle root project (_ROOT_)
* Create a new subproject of _ROOT_ (_SubA_)
* Create a new subproject of _ROOT_ (_SubB_)
* In _SubA_, create an empty interface called _ExampleInterface_
```Java
public interface ExampleInterface {}
```
* In _SubB_, create a class called _Example_
 * add the dependency of _SubA_ to _SubB_ (SubB/build.gradle):
```Text
dependencies {
    compile project(':SubA')
}
```
 * add the interface to the class
```Java
public class Example implements ExampleInterface
```
* Use fix imports via Netbeans IDE
* Compile source code of _SubB_

### Expected behaviour

* Import of _ExampleInterface_ from _SubA_
* Editor error 'cannot find symbol: class ExampleInterface' disappears
* Code compiles

### Actual behaviour

* Importing _ExampleInterface_ fails
* Editor error stays
* *But*: code compiles

**Comment by kelemen** [comment]
You have to reload the project after adjusting project dependencies (context menu of project/Reload Project).

**Comment by f-stoffel** [comment]
Jepp, you are right.

Maybe there is a way to automate the project reload? In projects with many sub-projects, doing this manually is very tedious...

**Comment by kelemen** [comment]
It is only done automatically when NB starts. This is because there is no reliable way to detect that it should be done (and reloading the project is a somewhat heavy operation for large projects).

Anyway, as is currently, all opened projects of the same project tree will be reloaded when you reload a project.
