### ISSUE TITLE
Any way to tweak the project node name/label?

### ISSUE THREAD

**Issue by fwelland** [kelemen/netbeans-gradle-project#171]
Hi, 

I have been using G4NB in large multi-project build, for some time.   Works well.    However, we have sub-projects (their directories) that have the same name:

```
root
     sub1
         ejb
         war
    sub2
         ejb
         war
```

When G4NB makes project nodes, it uses the gradle project name -- which mean I get more than one node named 'ejb' or 'war'.   

Is there any simple tweak I can do to affect the naming?

**Comment by JustGregory** [comment]
I would like to see this as well. For one, simply prefixing the parent name before the individual project name might work; for others, setting the project display name in the build file is useful. But it would be nice to use something built-in so that I don't have to have a line setting the project display name string.

**Comment by ironduke71** [comment]
Hi,

I had a similar question previously and I ended up making a temporary
change to the plugin to show the module names in the format A:B:C. Changes
to NbGenericModelInfo and SubProjectsChildFactory attached as well as the
nbm. It's not perfect, some areas still only show the leaf project name
instead of the full path. It's also a bit buggy where opening projects for
the first time doesn't sort, but if you switch project groups or add child
nodes it refreshes and sorts the projects properly.

**Comment by fwelland** [comment]
Project Display Name?    Elaborate...

More on the back story of the request:  I have large  code based I've migrated from   CVS/ANT to GIT/Gradle.   I have some 60+ gradle files in my project.     I have about 15 peeps in my project with somewhere around a 65% eclipsers and 30% NB peeps and InteliJ dude.   

I don't get the eclipse dudes, as being a NB peep I tend to open gradle sub projects selectively based on tasking and don't often have subs open that promote the duplicate name confusion...  But working with my eclipse colleagues they tend to have all the 60+ projects open all the time.    I think it is inherent on how eclipse does gradle.   At any rate, the gradle for eclipse thing (and its gradle plugin) does something to prevent the dup names.  However, it sames the last dup 'looses'; not getting a prefix while others seem to get prefixed with a parent projects name.....

Further the eclipse gradle plugin; one can do this:
```
 eclipse {
   project {
     name = 'projectNameInEclipse'   //getPath() seems to work; makes names like A:B:C as suggested above..
    }
}
```
And the generated eclipse project will have a nice name and the vanilla gradle stuff is pretty much unaffected.      I think the idea plugin has a similar thing.   

In vanilla gradle,   project.name is immutable --- or so it seems and there isnt' away to have a settings.gradle at the sub-project level that complements what is at the root.    

Since G4NB is pretty intelligent and doesn't generate a project that can fall out of synch with gradle.build like what eclipse does (and inteliJ I think); using gradle files directly.    It would be great if there is some innocuous nugget I can add to my gradle that I can use to help control the project node name ....  

FWIW:  using nb8; all the latest plugins JDK 7 and Gradle 2.2x

**Comment by fwelland** [comment]
Following @ironduke71  comments I updated the else block in https://raw.githubusercontent.com/kelemen/netbeans-gradle-project/master/netbeans-gradle-plugin/src/main/java/org/netbeans/gradle/project/model/NbGenericModelInfo.java:148  to look like this: 
```
            String scriptName = (isRootProject() ) ? getMainProject().getProjectName() :  getMainProject().getProjectFullName(); 
            scriptName = scriptName.trim();
            if (scriptName.isEmpty()) {
                scriptName = getProjectDir().getName();
            }

            if (isRootProject()) {
                return NbStrings.getRootProjectMarker(scriptName);
            }
            else {
                if(scriptName.charAt(0) == ':')
                    scriptName = scriptName.substring(1); 
                return scriptName;
            }
```
Opened projects will then have the full 'gradle-project-path' but without the leading ":".      I didn't mess with the sub-project tree display stuff -- as I didn't see that as a problem since the project hierarchy is preserved visually but nature of the tree display. 


*NOTE:*   why did I leave off of leading ":"?    Because eclipse.    Eclipse (don't use, but eclipse heads are all around me)  has a gradle plugin that generates an eclipse project.   Eclipse then uses the generated project to actually 'do eclipse'.    However, Eclipse chocked on leading ":" and I think internal ":" too.    So I chopped it off (and converted the internal ":" to ".").    This was slightly simpler than the plugin hack for NB and was accomplished via (in case you are wondering): 

```
subprojects {
apply plugin: 'eclipse'
......

ext.friendlyProjectName = getPath().replaceAll(':', '.').substring(1)

    eclipse {
        project {
            name = friendlyProjectName
        }
    }
}
```

**Comment by kelemen** [comment]
Given your comment I just realized that the plugin may even check if there is a "netbeansDisplayName" or (projectDisplayName or whatever) property is set and uses that for project display name. This has the advantage that users don't need to manually configure a display name for the project. And the obvious disadvantage is that it cannot be configured per user.

**Comment by kelemen** [comment]
The project name is now customizable the same way as it is done in Maven projects. However, I cannot push to Github at the moment, so the changes are not yet uploaded. If you think there should be other ways to customize the name, feel free to recommend new pattern variables.
