### ISSUE TITLE
System.in does not provide input from Netbeans output window when used in build.gradle

### ISSUE THREAD

**Issue by Barteks2x** [kelemen/netbeans-gradle-project#172]
When System.in is used in build.gradle it doesn't work on Windows. I works correctly on linux. 
It doesn't work when I run project too even if I add:
standardInput = System.in
to build.gradle run task.

Netbeans 8.0.2, Windows 8.1 (tested on Windows 7 too), plugin version: 1.3.2
java version:
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b18)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

Everything works correctly with non-gradle projects.

**Comment by kelemen** [comment]
This is a bug in Gradle: https://issues.gradle.org/browse/GRADLE-2462

That is, the input is only forwarded after you press "Ctrl + D" (i.e., when you close the input stream).

**Comment by Barteks2x** [comment]
But after pressing ctrl+d netbeans output window no longer accepts input. 
I found a workaround to this issue. Instead of starting java normally I start it in new windows console:
if(System.getProperty("os.name").toLowerCase().contains('win')){
        executable 'cmd'
        jvmArgs '/C'
        jvmArgs 'start'
        jvmArgs 'java'
}
For debug mode I need to manually attach debugger.

**Comment by kelemen** [comment]
Yes, Ctrl+D does not allow more input, so is not a solution (just wanted to tell how it works).
