### ISSUE TITLE
Heap Size when running tests from within netbeans

### ISSUE THREAD

**Issue by MikaelUmaN** [kelemen/netbeans-gradle-project#174]
Hello.

Upon executing "run focused test method" on a memory intensive test I encounter "OutOfMemory" error due to insufficient heap space.

Is there any way to configure java VM options (e.g. Xmx) so as to allow more memory when using the auto-generated javaexec tasks (that is, running from within netbeans).

**Comment by kelemen** [comment]
You have to configure the JVM arguments in the global settings for the daemon. It is -Xmx1024m by default (which is usually a lot more than you need). Note that you need to kill the Gradle daemon process(es) to apply the config.

The auto-generated "run" task does not allow to configure the JVM arguments (you have to write your own, if you want to).

**Comment by MikaelUmaN** [comment]
Thanks!
