### ISSUE TITLE
Feature Request: Scrollable tasks list context submenu.

### ISSUE THREAD

**Issue by JustGregory** [kelemen/netbeans-gradle-project#175]
A general idea for @kelemen or anyone else who would like to improve the UI. This is not so much a "bug" as it is more a problem in the context menu entries for showing the gradle tasks. But it is "reproducible" by following my mentioned workflow, below.

Use case: I develop some Minecraft mods, which depends on the MinecraftForge/ForgeGradle build components, projects here on Github. (The latest recommended Minecraft mod template project is found at http://files.minecraftforge.net/ by downloading the `1.7.10-Recommended` file `Src` link.) After the default `build.gradle` sets up repository dependencies, one of the first entries is a line to `apply plugin: 'forge'` (in fact it's the only plugin applied by default). The ForgeGradle tasks, though, are quite numerous; if right-clicking on the project and attempting to browse the tasks that are accessible in the context menu, I noticed that the submenu items are not scrollable, although I **can** arrow-key navigate to off-screen entries without knowing what is what. And since the latter items (in a Minecraft+Forge+Gradle setup anyway) scroll way off-screen in my 1366x720 screen, I am at a loss as to what task would be selected from arrow-key navigation past the bounds of the screen.

How to fix it depends upon how you prefer to display the lengthy list of tasks. In some applications with complex context menus, I've seen either scroll-marks at the top and bottom of what is shown on screen; in others, I've seen that the list is broken into multi-columns for the submenu items. Either, if feasible as a solution, would be acceptable to me; or if some other methodology of handling this issue is possible, I'm willing to give further feedback.

Is this within possibility of being looked into? I love this NetBeans Gradle plugin as much as you do; and though I imagine not a lot of its users may need quite so many entries in the Tasks submenu, it's something that is a source of frustration. The thing is, I've noticed this issue for some time, but always thought perhaps someone else who uses a build setup with a number of tasks would have said something by now. After briefly looking through the issues list and not finding something similar, I decided now would be as good a time as any.

**Comment by kelemen** [comment]
Most likely, will be fixed. This problem is in one of the top issues. Until then, you probably should define custom tasks.

**Comment by kelemen** [comment]
Although, the menu is not yet scrollable, tasks are now automatically grouped by their name (see my last comment in #104).

**Comment by kelemen** [comment]
I will consider grouping of tasks as a fix. If it is still not enough for someone: Open another issue.
