### ISSUE TITLE
NetBeans ignores sourceSets specs

### ISSUE THREAD

**Issue by wvreeven** [kelemen/netbeans-gradle-project#184]
For historic reasons all source code files in my projects reside inside the src directory. However, all test classes are inside <package>/test subdirectories (yuck, I know...).

I added a sourceSets definition in the build.gradle file which gets respected when building and testing with Gradle, both from the command line and from within NetBeans. However, the Projects tab shows all source files both in the Source Packages and Test Packages trees. This is how I defined the sourceSets:

    sourceSets {
        main {
            java {
                srcDir 'src'
                exclude '**/test/'
            }
        }
        test {
            java {
                srcDir 'src'
                include '**/test/'
            }
        }
    }

**Comment by kelemen** [comment]
Exclude and include patterns are currently ignored by the plugin. Also, currently class path detection will ignore this info as well. This is most likely fixable. If you write me a method which determines if a file (or directory) is in a source root (given the source root path, exclude and include rules), I will make the plugin consider exclude and include patterns. Otherwise, this is a low priority issue because you are the first one requesting it.

By the way, instead of writing `srcDir 'src'`, you should write `srcDirs = ['src']`. Otherwise, Gradle will check the default source root as well (not that it matters much).

**Comment by wvreeven** [comment]
Thanks for the quick reply and the advise you gave me about improving my build.gradle file. I understand it is a low prio issue and I'll consider looking into the method you requested.

**Comment by kelemen** [comment]
Should be fixed in master. Can you verify it works for you? (i.e., clean and build the project and install the created nbm).If it doesn't work, try clearing NetBeans' cache folder.

**Comment by gallardo** [comment]
> By the way, instead of writing srcDir 'src', you should write srcDirs = ['src'].

@kelemen Thanks! This is priceless!

**Comment by gallardo** [comment]
Uhmmm... I cannot understand why the directories are not filtered?

I'm including only `org/opencms/ade/containerpage`:
```gradle
// ...
sourceSets[...+'_gwt'].java.srcDirs=["$gwtDir"]
sourceSets[...+'_gwt'].java.include 'org/opencms/ade/containerpage/**'
// ...
```

But I see all other directories (their content is correctly filtered, though). Current tree:
![image](https://cloud.githubusercontent.com/assets/790448/9607958/3e4cf76a-50cc-11e5-804f-f28a7112685e.png)
Expected:
![image](https://cloud.githubusercontent.com/assets/790448/9608355/4dfcd502-50ce-11e5-8c34-d26430d42bfe.png)



I have checked `org.netbeans.gradle.project.util.ExcludeIncludeRules` and it looks pretty good (it filters out correctly the files that have not been included), but I don't understand yet how the `isAllowAll` is supposed to work...

**Comment by kelemen** [comment]
Only files are filtered and not directories. The reason for this is because you can - in theory - create complex rules to reinclude subfolders/files and the only way to check it is to check all the files in the source which would extremly inefficient (though there could be some rule of thumbs to detect common patterns). As for `isAllowAll`, it is simply for optimization purposes to cut some code paths when there are no rules (which is the most common case).

**Comment by kelemen** [comment]
I think, I might add some optimization if there are no "include" rules, if that is what you want.

**Comment by kelemen** [comment]
or if there are only include rules.

**Comment by gallardo** [comment]
>  you can - in theory - create complex rules to reinclude subfolders/files and the only way to check it is to check all the files in the source which would extremly inefficient
I though all files are checked anyway. I'm afraid that without a complete understanding of how the plugin works it's not easy to follow this explanation.

> I might add some optimization if there are no "include" rules
In my case, there are only include rules. But again, out of curiosity, you are already testing for all include and exclude patterns (at least, that is what `org.netbeans.gradle.project.util.ExcludeInclude.includeFile(...)` suggest). What am I missing?

**Comment by kelemen** [comment]
Originally, the plugin did not support these patterns. To keep the same performance, I have to instantiate different classes if there are no rules. The one you need, is an additional check (and maybe an additional classpath, etc. implementation).

**Comment by gallardo** [comment]
I'm almost giving up: I have found how the plugin updates the sources (`GradleClassPathProvider.updateAllSources()`) apparently building a list of `PathResourceImplementation`. For `JavaSourceGroups` with declared include/exclude filters, it instantiates `ExcludeAwarePathResource`, that implements NB's `FilteringPathResourceImplementation` interface.

So far, so good. From my observations, for my project I have a `JavaSourceGroup myModule.mySourceSet.JAVA` with a `FilteringPathResourceImplementation` with include pattern "/blah/blah/**". I'd now have expected that NB invokes the `FilteringPathResourceImplementation.includes(urlRoot, resource)` for each file/dir. But this doesn't seem to be the case. I have added some logs, but these are never printed out. :open_mouth: 

So my question: where does NB test if a resource belongs under the corresponding sourceSet tree node? I must be looking at the wrong place!

**Comment by kelemen** [comment]
Those are only for the classpath and not for displaying the source nodes. For displaying the sources in the project view (I believe) the only thing that matters is `GradleSourceGroup` within `GradleProjectSources`.

**Comment by gallardo** [comment]
Thank you!

**Comment by gallardo** [comment]
Now I understand your comments. And no, the solution doesn't seem to be very straightforward.
