### ISSUE TITLE
Allow adding .jar runtime dependencies in IDE without modifying build.gradle

### ISSUE THREAD

**Issue by Barteks2x** [kelemen/netbeans-gradle-project#201]
In some projects (at least the projects I'm working on) some runtime dependencies can't be downloaded automatically and have to be compiled loacally.
Currently the only way to make it possible to run such project is to locally modify build.gradle and add runtime files('location'). 
All other IDEs I know allow to do it (Eclipse - build path, IntelliJ IDEA - module dependencies). 
It makes it really hard to run some gradle projects using Netbeans.

**Comment by kelemen** [comment]
I'm not sure what you want. Why do you have the build script, if you are relying on the IDE? That is - if I uderstand you correctly -, your build script is broken. Why don't you instruct Gradle to compile those projects?

**Comment by Barteks2x** [comment]
They can be compiled, but running them is completely different thing. Compile time dependencies have to be created locally (and in my case, some compile time dependencies too).
And I'm working with a few other people and only I use Netbeans. They don't want to modify buildscript just to support Netbeans.

**Comment by kelemen** [comment]
I still don't quite understand why it isn't a build script issue. I mean, the build script doesn't have to be modified for NetBeans but modified in order to describe the project properly. Why is it not possible to add a runtime project dependency or the output of a java compile task? If you look at all of NetBeans project types, you can see that NetBeans builds on the idea that the build script is god. Please, don't take it as an offense but I don't want to break this core principle because the build script of your project is incorrect. That is, the runtime dependencies in the build script are incorrectly declared.

**Comment by Barteks2x** [comment]
Myself I really like the idea of netbeans IDE<->gradle integration, when the whone bahavior of IDE is based on buildscript. When I first used netbeans with gradle I was amazed that running my project just worked when I specified main class in buildscript. And the way it works in eclipse is exactly the reason I hate it's gradle and maven intergation for - there is no easy way to make gradle handle running my project. 

The way it works in Netbeans works well for simple projects, projects that have a few dependencies or when the dependencies are all in some public repository.

But in practice sometimes it just isn't very good solution.

Without an example it may be hard to understand, so I will just give an example here:
I'm writing a plugin for [Sponge server](https://github.com/SpongePowered/Sponge). I compile my plugin for some API. And then implementation is used to run it. 
The idea is that plugin is written once, for [one API](https://github.com/SpongePowered/SpongeAPI) and you can use it on any implementation (currently there are 2 implementations).
Implementations are separate projects, they use gradle but they don't have maven repository.
In order to make buildscript fully handle running it it would need:
*clone git repository
*run gradle buildscript for this project to set it up
*somehow incluse it as dependency
*run GradleStart class

It seems like [1]nobody else repotred it because nobody really uses netbeans for such projects. Nobody uses it for such projects because of this problem. GOTO 1.

Of course I can talk to authors of Sponge project to make it a bit easier. But they probably won't make any big changes just for a few people/just for me. 
And it looks like this plugin won't get this feature for exactly the same reason.

I will understand it if it won't be implemented. I only thought it won't harm to at least try.

**Comment by kelemen** [comment]
There is a workaround for this use-case (which I think is better than break the whole concept of this plugin): You can add a global init script which checks if the project is your particular project and if it is, adds the required runtime dependency. That said, I can consider a project property which allows you to specify an init script used for only that project (although, you can already do this for built-in commands like "run").

**Comment by Barteks2x** [comment]
Now I only need to know how to incluse other gradle project as dependency from init script.
The only way to do it I found requires modifying settings.gradle.

**Comment by kelemen** [comment]
You cannot do that from the init script what you can do is:

1. Add the compilation output directory of your project as a dependency.
2. Add a [`GradleBuild`](https://gradle.org/docs/current/dsl/org.gradle.api.tasks.GradleBuild.html) task dependency to the approriate `compileJava` task which compiles your project dependency.

This should work as you expect it to work.

**Comment by Barteks2x** [comment]
Is it possible to use transitive dependencies too? They aren't in compilation output directory. The best would be to get the value of sourceSets.main.runtimeClasspath of my dependency and add it to classpath.
I also tried to add something to print the classpath of my dependency when running it and add it's contents to my project. There are some weird asm transformations related exceptions. At this point - I give up. I will simply use other IDE.

**Comment by kelemen** [comment]
I'm sorry I couldn't help but your use-case seems too special (and I think the core project you are using is wrong to force you do this).

Another thing to try (even if you are using another IDE like IntelliJ): You can create a new multi-project build to which you can include both your and the core project and also create another project which depends on both. This way, the project can be imported to IDEs without manual modifications needed after importing (if you don't count creating the extra project and settings.gradle). Though, I agree that using IDEA for your project is probably the most simple.
