### ISSUE TITLE
Empty build.gradle and settings.gradle

### ISSUE THREAD

**Issue by jpete** [kelemen/netbeans-gradle-project#202]
Netbeans : 8.0.2 (Build 201411181905)
Gradle Support :  1.3.5
Gradle : 2.4
JDK : 1.8.0_31
OS : Windows 8 version 6.2 (Had same issue on Windows 7)

I updated the plugin. Tried to create a new single application. The build.gradle and settings.gradle file is empty other than   \   at    1:1.

Here is the stacktrace. -> [Stacktrace](https://gist.github.com/jpete/d15fec4cb98bbb17bbfb)

After I added added valid build script everything worked fine.

**Comment by kelemen** [comment]
Do you mean, that you have created a new "Single Gradle Project" with the wizard or did you create the project by hand?

**Comment by jpete** [comment]
With the wizard.

**Comment by kelemen** [comment]
I cannot reproduce the issue (works fine for me). Can you think of anything special about you config? Say, what locale are you using, what rights your user have, etc.?

**Comment by jpete** [comment]
No. I can't think of anything that would be causing it. I'm using english locale, with admin rights. I just created a directory and gave full control to everyone, and tried to create a single project there. All others files and directories were created, but the settings and build only had a \ .

Here is everything that was created. -> https://s3-us-west-2.amazonaws.com/jpete.storage/Test.zip

**Comment by kelemen** [comment]
I have found the bug. This only happens on Windows. Currently, there is only one workaround: Install the "Change Line Endings on Save" plugin and set it to use LF line endings. I have fixed the issue in master.

**Comment by jpete** [comment]
Thanks
