### ISSUE TITLE
Custom Tests menu not working

### ISSUE THREAD

**Issue by imartinbe** [kelemen/netbeans-gradle-project#203]
Hi,
I have created 2 custom tests *integTests* and *dialogTests* :
```groovy
test{
excludes = ['integtests/**','dialogtests/**']
}
task integTest(type : Test){
    ignoreFailures = isJenkins
    include 'integtests/**'
}

check.dependsOn integTest

task dialogTests(type : Test){
    include 'dialogtests/**'
}
```
With the new version of the plugin, a new menu has appeared : 
* Custom Tests
  * integTest
  * dialogTest

The problem is that clicking on any of them will run the task
```groovy
gradle cleanTest test
```
and not the one selected...

**Comment by imartinbe** [comment]
I found the trick : I need to update my profile to add the *${test-task-name}* argument in place of test...
I close the issue.

**Comment by kelemen** [comment]
Most likely you have customized the built-in test command which should be something like this `${project}:clean${test-task-name-capital} ${project}:${test-task-name}`.
