### ISSUE TITLE
[HOWTO] How to manipulate gradle command line settings from another NetBeans module?

### ISSUE THREAD

**Issue by rafalkrupinski** [kelemen/netbeans-gradle-project#204]
Hi
Could someone give me some tips on how to modify the Gradle arguments (as seen in tools/options/Misc/Gradle/Script & Tasks) programmatically from an another module?

Thanks

EDIT I meant programmatically not grammatically :)

**Comment by kelemen** [comment]
I'm not sure what you mean on "from an another module". The settings there are applied to any Gradle command. In the project properties, you can customize each built-in commands where you can specify other arguments. What exactly do you want to achieve?

**Comment by rafalkrupinski** [comment]
I want to edit that field programmatically, using NB/gradle plugin APIs. I need to propagate one of the settings from my module to Gradle, so users don't have to enter it twice (and possibly introduce error).

**Comment by kelemen** [comment]
On another module do you mean another NetBeans plugin? If so, I don't think there is a way to do that (other than explicitly overwriting the settings were this property is saved to). However, if you need something like this, we can work out a better solution.

**Comment by rafalkrupinski** [comment]
> On another module do you mean another NetBeans plugin? 

Yes

> explicitly overwriting the settings were this property is saved to

I think that would do for now. How can I access it?

**Comment by kelemen** [comment]
Preferences preference = NbPreferences.forModule(org.netbeans.gradle.project.api.entry.GradleProjectExtensionDef.class);
    // on preference you can get and set an entry using the keys: "gradle-args" and "gradle-jvm-args".

You will have to depend on my plugin which is uploaded in the *http://dl.bintray.com/kelemen/maven* maven repository (the artifact is "com.github.kelemen:netbeans-gradle-plugin:1.3.6").

Note however, that if you do this when saving something in the global settings, you will race with my plugin overwriting this value.

**Comment by kelemen** [comment]
On the long run, can you describe your exact use-case, so that we can design a more reasonable solution.

**Comment by rafalkrupinski** [comment]
What do you mean by race condition? If my plugin changes this setting (in response to user saving options), wouldn't it get reflected in the Gradle plugin?

> On the long run, can you describe your exact use-case, so that we can design a more reasonable solution.

My plugin requires external application and users need to configure its home in the options. There are also Gradle projects that require that application and need -Dapp.home=... passed to Gradle. Currently users set app.home twice: in Gradle arguments and in my plugin's options, but I want to avoid it.

**Comment by kelemen** [comment]
What do you mean by race condition?

I mean that when the user applies the global settings dialog, NB will iterate over the modules to apply their settings. My module will read what is on the UI and overwrite the settings and presumably yours would too. So which takes effect depends on the order NB calls the module's `OptionsPanelController`.

**Comment by kelemen** [comment]
Is it reasonable to base your arguments on a project? That is, is there any benefit for you to be able to provide different arguments for different projects?

**Comment by rafalkrupinski** [comment]
> NB will iterate over the modules to apply their settings. My module will read what is on the UI and overwrite the settings and presumably yours would too

Good point

> Is it reasonable to base your arguments on a project?

No, it's a global setting

**Comment by kelemen** [comment]
I will think of some solution to allow other plugins to specify Gradle arguments in a few days. I will probably make the settings project dependent just in case (it just means that you have to return the same for all projects).

**Comment by kelemen** [comment]
There is one thing what you do know which only works when executing tasks but not when evaluating the project to be loaded. That is, you specify an init script where you can set these properties. Is this enough for you?

**Comment by rafalkrupinski** [comment]
I don't see how Gradle init script could help here. Either the user has to maintain it (may diverge) or my plugin (what if there's other contents?).

**Comment by kelemen** [comment]
Your plugin can generate the content of the init script on the fly, it doesn't have to be created at compile time.

**Comment by kelemen** [comment]
I have added a new API to allow extensions to provide arguments (and JVM arguments) using the `GradleArgumentQuery` query.

**Comment by kelemen** [comment]
If you need help how to add the query, just drop me a mail.

**Comment by rafalkrupinski** [comment]
Thanks a lot, will do.
