### ISSUE TITLE
generated files in error

### ISSUE THREAD

**Issue by aplatypus** [kelemen/netbeans-gradle-project#206]
Hi,

I have the latest Gradle plugin with Netbeans 8.0.2.  I have Gradle v2.04 installed.

Every new project generated gradle files begin with a slosh(\) on the first line.

*  settings.gradle
*  build.gradle, and
*  common.gradle

All look like single line:

      \

I checked the templates settings - There are no gradle templates used, so I'm thinking it is a  code issue.

regards,
Will

**Comment by kelemen** [comment]
This is already fixed, please update to the latest version of the plugin (it should be already up in the update center).

**Comment by aplatypus** [comment]
The error occurred with the 'latest update', as of yesterday.  There was a new update tonight which I installed.

The "New Project" / Groovy Single now creates a Build.gradle file all on a single line:

      apply plugin: 'java'\\sourceCompatibility = '1.8'\[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'\\// NetBeans will automatically add "run" and "debug" tasks relying on the\// "mainClass" property. You may however define the property prior executing\// tasks by passing a "-PmainClass=<QUALIFIED_CLASS_NAME>" argument.\//\// Note however, that you may define your own "run" and "debug" task if you\// prefer. In this case NetBeans will not add these tasks but you may rely on\// your own implementation.\if (!hasProperty('mainClass')) {\    ext.mainClass = ''\}\\repositories {\    mavenCentral()\    // You may define additional repositories, or even remove "mavenCentral()".\    // Read more about repositories here:\    //   http://www.gradle.org/docs/current/userguide/dependency_management.html#sec:repositories\}\\dependencies {\    // TODO: Add dependencies here ...\    // You can read more about how to add dependency here:\    //   http://www.gradle.org/docs/current/userguide/dependency_management.html#sec:how_to_declare_your_dependencies\    testCompile group: 'junit', name: 'junit', version: '4.10'\}\

I used Notepad++ to view all characters - No CRLF, LF or TAB-s.  So the generating template (or such) isn't doing an end of line.

**Comment by kelemen** [comment]
Thank you, for the report this was a dumb mistake. I have fixed it in master.

**Comment by kelemen** [comment]
Until next release, you can install the "Change Line Endings on Save" plugin and configure the line ending to your preference.
