### ISSUE TITLE
Duplicate .java files appear in Other Sources

### ISSUE THREAD

**Issue by joebowbeer** [kelemen/netbeans-gradle-project#207]
If java.srcDirs and resources.srcDirs both point to 'src' as they sometimes do, I'm seeing the Java files listed twice, once in Source Packages src and once in Other Sources src.

I don't think this should be happening because the "resources" source set is defined to contain only resources, excluding any .java files found in the resource source directories. Likewise the java srcDirs is probably restricted to contain only .java.

http://gradle.org/docs/current/userguide/java_plugin.html

By the way, it is not uncommon for the java.srcDirs and resources.srcDirs to be equivalent, or for the resources dirs to also contain Java source files. This is now common in Android projects that are migrated to Gradle, using the boilerplate:

    sourceSets {
      main {
        manifest.srcFile 'AndroidManifest.xml'
        java.srcDirs = ['src']
        jniLibs.srcDirs = ['libs']
        resources.srcDirs = ['src']
        aidl.srcDirs = ['src']
        renderscript.srcDirs = ['src']
        res.srcDirs = ['res']
        assets.srcDirs = ['assets']
      }
    }

The first two attached image show an Other Sources tree that displays a copy of Java Packages tree. This corresponds to other srcDirs referencing the Java 'src' folder. In the final attached image the Other Sources tree is gone.

![netbeans1](https://cloud.githubusercontent.com/assets/28679/7668929/3bb0a8ea-fc0c-11e4-9551-0b1d83867eb9.png)
![netbeans2](https://cloud.githubusercontent.com/assets/28679/7668930/3bb1e41c-fc0c-11e4-9dd3-1354da984a6a.png)
![netbeans3](https://cloud.githubusercontent.com/assets/28679/7668931/3bb3983e-fc0c-11e4-85b1-058dc7a1eafa.png)

**Comment by kelemen** [comment]
For Java projects you can explicitly tell Gradle to exclude *.java* files from the resources source set and this will be recognized by this plugin:

    sourceSets.main.resources.exclude '**/*.java'

However, if you are working with Android projects, then nodes are not generated by this plugin but the Android plugin and I don' know what exactly the Android plugin considers.
