### ISSUE TITLE
org.gradle.parallel enabled causes lingering JVM processes

### ISSUE THREAD

**Issue by dorknexus** [kelemen/netbeans-gradle-project#210]
I have a multi-project build with org.gradle.parallel enabled in my gradle.properties file.  When I execute multiple applications in parallel from the terminal (using "gradle run")  I see two JVM processes appear for each invocation of "gradle run".

I expect to see two processes appear as one is gradle, and one is the java application running.  When I terminate the java program running, both processes die.

However, when I run the applications from within netbeans, one of the JVM processes will linger around indefinitely after program close.  Not sure what the cause is.

**Comment by kelemen** [comment]
What you are seeing is the Gradle daemon and is a normal behaviour. Read more about it in the [Gradle docs](https://docs.gradle.org/current/userguide/gradle_daemon.html).

**Comment by dorknexus** [comment]
This is disabled by default though so why is it enabled in the plugin and is there a way to disable it?

**Comment by kelemen** [comment]
This cannot be disabled when an IDE executes a Gradle command through Gradle's API. There is call which (in theory) lets me use the IDE's process for the Gradle daemon (I have never tried it) but it will surely impose other limitations.

**Comment by kelemen** [comment]
Anyway having the daemon speeds up subsequent Gradle commands and model queries by a *lot*.

**Comment by dorknexus** [comment]
I understand the benefits of the daemon and I wouldn't mind having the process linger around.  However, for some reason every time I execute an application (even the same app with the exact some configuration) I get a new daemon process which consumes around 250 MB of memory.  It quickly becomes a problem.  For now I've just set the daemons to timeout after 1 minute (the lowest value possible in the plugin).  

Based on reading the doc you referenced though, it doesn't seem like a new daemon should be spawned every time.

**Comment by kelemen** [comment]
It definitely shouldn't spawn a new one always. Maybe you are executing applications with a different JDK which requires a new daemon to spawn (since the daemon can run only on one JDK). By the way, I recommend to set the maximum memory the daemon may use in the global settings (say, settings -Xmx512m for JVM arguments in the global settings) otherwise, the default 1GB.

**Comment by kelemen** [comment]
Are you sure that all those processes are Gradle daemons? I doubt that executing a Gradle command twice (not concurrently) on the very same project will spawn a new daemon (at least I have never seen such thing to happen).

**Comment by dorknexus** [comment]
I think I figured it out.  If I open the application once, then close it and reopen it it will use the same daemon process.  However, if I open the same application multiple times in parallel, each new instance of the same application will spawn a new daemon process.  So it seems that parallel execution of a program requires a new daemon process (which makes sense).  

Thanks for your help!

**Comment by kelemen** [comment]
Yes, that is true: A daemon can execute at most one task at a time.
