### ISSUE TITLE
Clear output on each build

### ISSUE THREAD

**Issue by whgibbo** [kelemen/netbeans-gradle-project#211]
Hi,
Great plugin means I can continue to you Netbeans as my IDE.
One question, is it possible to clear the output on each build?

Thanks

**Comment by kelemen** [comment]
Yes, you can check the "Always clear the output window" in the [Global Settings](https://github.com/kelemen/netbeans-gradle-project/wiki/Task-Execution).

**Comment by whgibbo** [comment]
Thanks missed that one, :)
