### ISSUE TITLE
[HOWTO] Attaching the sources of project dependencies

### ISSUE THREAD

**Issue by horvathandras** [kelemen/netbeans-gradle-project#213]
How does source attachement work with gradle projects?

I have a library which has it's distribution (jar) uploaded in the company's maven repository. I also uploaded the sources of the project with classifier 'sources'.

I can use the jar in a project if I add the artifact to the compile dependency, but the source code of it is not visible. The IDE has a feature to attach sources, but neither Zip/Folder attachment nor Download works. The local zip/folder doesn't seem to practical anyway, as the library is also in development phase so the snapshot is updated frequently. The download only pop's up an information panel that "No sources for mylib-1.0-SNAPSHOT.jar available". Does it search the same repository set up in the project's gradle file, or local maven repository?

(Using NetBeans 8.0.2, gradle support 1.3.6)

**Comment by kelemen** [comment]
For Maven/Ivy repositories, "Download sources" on the "Dependencies" node should download the sources into Gradle's cache and then the sources should be available in NetBeans.

**Comment by horvathandras** [comment]
Thanks for the fast response! I didn't come accross with that option before, it works perfectly.

**Comment by horvathandras** [comment]
I have just one more question in my mind regarding to this one:
When I create a new snapshot of my library I have to reload the dependent projects to notice the update then I also need to download the sources again to see the new version. Is there a mechanism or some kind of macro that I can make this procedure a bit more automatic with or at least make an automatic source download attempt on project reload?

**Comment by kelemen** [comment]
Currently, there is no automatic source download because source downloading is very poorly implemented. I might consider it after I have a better implementation for downloading the sources.

The best way for you would be to use project dependencies if possible. If it is not, currently the only way is reload + download sources.
