### ISSUE TITLE
Autocompletion does not work for jsf beans in the xhtml code

### ISSUE THREAD

**Issue by dremon** [kelemen/netbeans-gradle-project#216]
When using gradle war project in the Netbeans the IDE does not perform bean autocompletion inside xhtml files.

**Comment by fwelland** [comment]
may not be totally g4nb issue -- there seems to be some intrinsic issue in nb and facelets editing in projects that nb doesn't know the project type:  https://netbeans.org/bugzilla/show_bug.cgi?id=243617

**Comment by dremon** [comment]
Actually tag completion work fine for me (JSF, JSTL, Primefaces) but the "#{bean}" completion with CDI beans does not.

**Comment by dremon** [comment]
Another thing that might be related to thin problem: when I open WEB-INF/faces-config.xml in the editor there is an error message shown with the following text:
"Your faces configuration file does not exist within a Web Module. Page Flow Editor will not be able to properly model your project against actual files".

**Comment by kelemen** [comment]
The EE plugin should take care of web stuff. However, I think this is this issue: [netbeans-gradle-javaee-project: Issue 16](https://github.com/hildo/netbeans-gradle-javaee-project/issues/16).

**Comment by dremon** [comment]
Adding src/main/webapp/app directory (which contains xhtml files) to the sourceSets helped, thanks.
EE plugin doesn't work for me unfortunately - at least not for JSF project. When activated the JSF tags are not recognized.

**Comment by dremon** [comment]
If I add the entire 'webapp' directory to the sourceSet then the ee plugin works (my guess is that the missing xhtml templates are parsed correctly then).
One issue still remains though - how to let IDE autocomplete resource bundle defined in the faces-config.xml.
