### ISSUE TITLE
Add option to compiler Args

### ISSUE THREAD

**Issue by marccollin** [kelemen/netbeans-gradle-project#223]
hi

is there a way to add compiler arg to the build.gradle file?

i would like to add -Xlint:unchecked and -Xlint:deprecation

thanks

**Comment by kelemen** [comment]
You should add this to your build script:

    tasks.withType(JavaCompile) {
        options.compilerArgs = ["-Xlint:unchecked", "-Xlint:deprecation"]
    }

**Comment by marccollin** [comment]
continuer le travail

2015-07-24 8:09 GMT-04:00 Attila Kelemen <notifications@github.com>:
