### ISSUE TITLE
parent project with settings.gradle not working properly

### ISSUE THREAD

**Issue by jhogan515** [kelemen/netbeans-gradle-project#225]
Using Netbeans 8.0.2 and Gradle 2.4, there seems to be an issue with the settings.gradle file not working properly.

We have a top level project with several sub-projects.  When trying to open the top level project, the IDE gets stuck trying to load the project and never completes.  It doesn't load the sub projects either.

John Hogan
p.s. the basic structure looks like:

rootProject.name='my-project'

include 'sub-project-1'
include 'sub-project-2'
include 'sub-project-3'
include 'sub-project-4'

**Comment by kelemen** [comment]
Can you link a more specific example?

**Comment by jhogan515** [comment]
Hello Attila,

I'm not sure what I did,l but after closing out of Netbeans and re-opening the root project, I could then see the "Subprojects" folder, and I could then open each sub-project.  Please close this issue.  Thank you for the gradle plugin and for your help.

John Hogan

**Comment by kelemen** [comment]
Ok, please reopen this issue if it ever happens again.

**Comment by JustGregory** [comment]
Another thing about the example, instead of including each subproject manually, each on one line, we may put them on one 'include' line, as comma-separated items; and if the line gets long enough we wish to wrap to a new line, we use a slash character as a line-continuation symbol.
