### ISSUE TITLE
Tomcat embedded and code modification

### ISSUE THREAD

**Issue by marccollin** [kelemen/netbeans-gradle-project#227]
I use netbeans 8 and spring-boot. Tomcat embed 8 is used by spring.

When i do a change in a class, html... change is not take in consideration. I need to stop server and restart it.

Is there a gradle task i need to use instead of using run?

**Comment by kelemen** [comment]
I think you have to enable compile on save in the global settings: *Tools/Options/Misc/Gradle/Other*.
