### ISSUE TITLE
Not installable for NetBeans 8.1beta

### ISSUE THREAD

**Issue by juergenzimmermann** [kelemen/netbeans-gradle-project#228]
The Installation for NetBeans 8.1beta fails. I'll attach the screenshots.
![netbeans81beta 1](https://cloud.githubusercontent.com/assets/734334/9250947/d3943a0a-41d0-11e5-86a3-e78bb9c66b7d.png)
![netbeans81beta 2](https://cloud.githubusercontent.com/assets/734334/9250951/d9959412-41d0-11e5-980a-211151bb6f3f.png)

**Comment by kelemen** [comment]
This is a known, issue. Until now, you could use the NetBeans_nightly branch instead of master. However, at the moment there is no NetBeans 8.1 API to build against (i.e., it is not currently shared in any public repository). However, NB guys told me that they are working on sharing the dependencies, once they are done, I'll have a release for 8.1. Until then, sadly, you cannot use this.

**Comment by juergenzimmermann** [comment]
The link https://bintray.com/artifact/download/kelemen/maven/com/github/kelemen/netbeans-gradle-plugin/1.3.7.1.0/netbeans-gradle-plugin-1.3.7.1.0.nbm mentioned at readme.md works fine.

**Comment by kelemen** [comment]
Yes, thanks. Completely forgot about that build :)

**Comment by kelemen** [comment]
The dependencies are now available, so I'll have a release this evening.

**Comment by joebowbeer** [comment]
@juergenzimmermann - Gradle Support (nightly) installs in NetBeans 8.1 Beta, but Test fails because of gsf TestRunnerNodeFactory not being found.

Details:

https://netbeans.org/bugzilla/show_bug.cgi?id=253441
https://netbeans.org/bugzilla/show_bug.cgi?id=253531

**Comment by kelemen** [comment]
I think that should be fixed in the nightly and now there is also a NetBeans81 branch (you should use that). Anyway, I'll have a release for 8.1 soon.

**Comment by kelemen** [comment]
Fixed and uploaded to http://plugins.netbeans.org/plugin/44510. Also, as soon as the NB team verifies it, the plugin will be available from the plugins menu of NB.

**Comment by juergenzimmermann** [comment]
@kelemen Thank you very much!
The introduction at http://plugins.netbeans.org/plugin/44510 needs a slight update.

**Comment by kelemen** [comment]
Thanks, removed the unnecessary link.
