### ISSUE TITLE
Unable to resolve classes defined in plugins

### ISSUE THREAD

**Issue by gallardo** [kelemen/netbeans-gradle-project#231]
`org.netbeans.gradle.project.query.GradleHomeClassPathProvider.getGradleLibs` doesn't recurse into subdirs, so classes defined in gradle plugins are not resolved.

Example (using `maven` plugin):
![image](https://cloud.githubusercontent.com/assets/790448/9442045/ce931efc-4a79-11e5-83aa-419711ce22dd.png)

An it doesn't load classes in the dependencies defined for the `buildscript` either. For example:
```groovy
import com.helger.datetime.CPDT

apply plugin: 'maven'

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.helger:ph-datetime:4.2.0'
    }
}

task testbuildscriptdeps <<{
    println "Should be an int=org.joda.time.DateTimeConstants.MONDAY... "
    println "    CPDT.START_OF_WEEK_DAY = " + CPDT.START_OF_WEEK_DAY
}
```
is a working script, but the plugin cannot find `com.helger.datetime.CPDT`:

![image](https://cloud.githubusercontent.com/assets/790448/9462762/35c7eb40-4b18-11e5-8b5f-9f908777542c.png)

**Comment by kelemen** [comment]
Also, since the Groovy integration of NB does not allow me to specify implict imports, you have to explicitly import these classes. This is something I cannot fix. However, the recursive search is obviously fixable.

**Comment by gallardo** [comment]
I was trying to file a PR, but this is still too much black magic for me ;-) For instance: I cannot see how to get what plugins are installed.

**Comment by kelemen** [comment]
What do you mean on "installed"?

**Comment by gallardo** [comment]
I mean the e.g.
```
apply plugin: 'maven'
```
line in the build.gradle.

**Comment by kelemen** [comment]
You can query the properties of the `Project` instance similar to how [JavaTestModelBuilder](https://github.com/kelemen/netbeans-gradle-project/blob/master/netbeans-gradle-default-models/src/main/java/org/netbeans/gradle/model/java/JavaTestModelBuilder.java) does. However, I don't think there is any reason to do that for classpath purposes (i.e., applying them has no effect on the classpath).

**Comment by gallardo** [comment]
> applying them has no effect on the classpath

I didn't know it! It is a bit counter-intuitive, but I can confirm your statement:

```groovy
import org.gradle.api.artifacts.maven.MavenDeployment

// No need to declare the maven plugin!
// apply plugin: 'maven'

// Silly tasks to assert that org.gradle.api.artifacts.maven.MavenDeployment
//  is resolved if using maven plugin (#231)
task testplugindependencies <<{
    println MavenDeployer.class
}
```

So the patch for the _classes defined in plugins not resolved_ part of this issue report should be easy: the code should recourse into `gradle/lib/plugins` even if no plugin is defined.

**Comment by gallardo** [comment]
[I'm recurring into the `lib/plugin` dir](https://github.com/gallardo/netbeans-gradle-project/commit/64128171e06333a3bbae40fb01dba153d0e275a6) and now testing if anything breaks. It looks OK for the moment.

**Comment by eskatos** [comment]
> Also, since the Groovy integration of NB does not allow me to specify implict imports, you have to explicitly import these classes. This is something I cannot fix.

Here is the Netbeans issue: https://netbeans.org/bugzilla/show_bug.cgi?id=228173
Commented and voted for it, please push it forward so we have a chance for it to be included in a future Netbeans release.

**Comment by kelemen** [comment]
Sven Reimers is working on improving the Groovy integration of NetBeans. As much as I have seen, it looks promising.

**Comment by kelemen** [comment]
The plugin now adds the "lib/plugins" directory as well to the class path of .gradle files.
