### ISSUE TITLE
Missing dir dependencies 

### ISSUE THREAD

**Issue by gallardo** [kelemen/netbeans-gradle-project#234]
For the following build script, the plugin should ideally also show the directory dependency:

```groovy
apply plugin: 'java'

repositories {
    mavenCentral()
}

sourceSets {
    x {
        compileClasspath += files("$buildDir/classes/main") { builtBy 'compileJava' } 
        compileClasspath += files("lib/print.jar")
    }
}

dependencies {
    compile 'org.slf4j:slf4j-simple:1.7.12'
    xCompile 'org.slf4j:slf4j-simple:1.7.12'
}
```

(Notice the `compileClasspath += files("$buildDir/classes/main")` adding the classes directory)

![image](https://cloud.githubusercontent.com/assets/790448/9516745/0f90b9c2-4cab-11e5-9866-305a2fb10d04.png)

**Comment by gallardo** [comment]
The project compiles and builds without problem. The dependency is also found by NetBeans. This would be just a cosmetic improvement. In this project, the `x.compileClasspath` looks like:

    /home/alberto/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-simple/1.7.12/42..b0/slf4j-simple-1.7.12.jar
    :/home/alberto/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.7.12/8e..17/slf4j-api-1.7.12.jar
    :/home/alberto/src-tmpfs/kk4/build/classes/main
    :/home/alberto/src-tmpfs/kk4/lib/print.jar

**Comment by kelemen** [comment]
The output directory of other source sets are usually filtered because that's the only way I can tell that a source set depends on a project (for informational purposes only) and that a source set inherits from another source set (say, test excludes the dependencies of main). However, in this case I would expect that the plugin would say that x inherits main as it does for test. So, there is definitely a bug here, I'll have a look at it in the weekend.

**Comment by kelemen** [comment]
This should now work as I intended (i.e., says that "x" inherits "main" which is not true but in practical cases, it is).

**Comment by gallardo** [comment]
Weird.

Following build script is handled correctly:
```gradle
apply plugin: 'java'

sourceSets {
    x {
        java.srcDir 'src/x/java'
        resources.srcDir 'src/x/resources'
    }
    y {
        java.srcDir 'src/y/java'
        resources.srcDir 'src/y/resources'
        compileClasspath += files("lib/print.jar")
        runtimeClasspath += files("lib/print.jar")
        compileClasspath += files("$buildDir/classes/x")  { builtBy 'compileXJava' }
        runtimeClasspath += files("$buildDir/classes/x")  { builtBy 'compileXJava' }
    }
}
```
![image](https://cloud.githubusercontent.com/assets/790448/9578384/b80614e4-4fe9-11e5-96d1-746ad7e6a7c2.png)


But if `x` has also dependencies, it breaks the dependencies view (where is `y`?):
```gradle
apply plugin: 'java'

//repositories {
//    mavenCentral()
//}

sourceSets {
    x {
        java.srcDir 'src/x/java'
        resources.srcDir 'src/x/resources'
        // x has dependencies!
        compileClasspath += files("lib/print.jar")
    }
    y {
        java.srcDir 'src/y/java'
        resources.srcDir 'src/y/resources'
        compileClasspath += files("lib/print.jar")
        runtimeClasspath += files("lib/print.jar")
        compileClasspath += files("$buildDir/classes/x")  { builtBy 'compileXJava' }
        runtimeClasspath += files("$buildDir/classes/x")  { builtBy 'compileXJava' }
    }
}
```

![image](https://cloud.githubusercontent.com/assets/790448/9578411/0f9ab87c-4fea-11e5-8fe2-be0824a46737.png)

**Comment by gallardo** [comment]
compile/provided/runtime sections aren't correctly classified either:
```gradle
apply plugin: 'java'

sourceSets {
    x {
        java.srcDir 'src/x/java'
        resources.srcDir 'src/x/resources'
    }
    y {
        java.srcDir 'src/y/java'
        resources.srcDir 'src/y/resources'
        compileClasspath += files("lib/print.jar")
        runtimeClasspath += files("lib/print.jar")
        runtimeClasspath += files("$buildDir/classes/x")  { builtBy 'compileXJava' }
    }
}
```
![image](https://cloud.githubusercontent.com/assets/790448/9578492/b973a5de-4fea-11e5-821d-4fbf78353ed0.png)

`y` should only 'inherit' `x` in runtime.

**Comment by kelemen** [comment]
Your first example: The "y" node is missing because it would be empty (only marked as inherits "x"), so it is simply trimmed (this is an intended behaviour).

As for the second example: The plugin assumes that inheritance is between source sets, so if either compile, runtime or provided inherits, all node will be marked. This is a case I have considered but decided against complicating the "inherit" mark because I didn't think it is of any practical importance. Is it a practical issue for you, or is it just theoretical?

**Comment by gallardo** [comment]
First of all
> is it just theoretical?
For the moment being, I'm testing this patch, so it's only a theoretical contrived example. (But I'm afraid my real case is more complex).

> The "y" node is missing because it would be empty (only marked as inherits "x")
I'm not sure: it doesn't inherit from `main`, so I feel like if it still were a bug.

**Comment by kelemen** [comment]
The all "inherits" is just determined by a rule of thumb: The dependency set contains the classes output dir of another source set. (anyway, this inheritance is just for display, NB won't rely on it for classpaths). The rule of thumb is used because I don't know any reasonable way I can detect if there was an explicit inheritance declared.

**Comment by gallardo** [comment]
I still don't get it. Say I have only `main` and `x`. When NB signals for `x` the `inherits main`, does it mean it uses only its build path, or its build path _plus_ its libraries? In my tests, this doesn't seem consistent:

#### Case 1: `X` depends on the `main` outputDir, and on all other `main` dependencies

```gradle
apply plugin: 'java'

repositories {
    mavenCentral()
}

sourceSets {
    main {
        compileClasspath += files("lib/print.jar")
        runtimeClasspath += files("lib/print.jar")
    }
    x {
        java.srcDir 'src/x/java'
        resources.srcDir 'src/x/resources'
        compileClasspath += files("lib/print.jar")
        runtimeClasspath += files("lib/print.jar")
        compileClasspath += files("$buildDir/classes/main") { builtBy 'compileJava' }
        runtimeClasspath += files("$buildDir/classes/main") { builtBy 'compileJava' }
    }
}

dependencies {
    compile 'org.slf4j:slf4j-api:1.7.12'
    runtime 'org.slf4j:slf4j-simple:1.7.12'
    xCompile 'org.slf4j:slf4j-api:1.7.12'
    xRuntime 'org.slf4j:slf4j-simple:1.7.12'
}
```
OK, there is no `Compile/Runtime for x` because its empty apart from `inherits from main`:
![image](https://cloud.githubusercontent.com/assets/790448/9579527/a49cc920-4ff3-11e5-9f0b-521e94255752.png)


#### Case 2: `X` depends on the `main` outputDir, but doesn't include the libraries `main` depends on
```gradle
apply plugin: 'java'

repositories {
    mavenCentral()
}

sourceSets {
    main {
        compileClasspath += files("lib/print.jar")
        runtimeClasspath += files("lib/print.jar")
    }
    x {
        java.srcDir 'src/x/java'
        resources.srcDir 'src/x/resources'
        compileClasspath += files("$buildDir/classes/main") { builtBy 'compileJava' }
        runtimeClasspath += files("$buildDir/classes/main") { builtBy 'compileJava' }
    }
}

dependencies {
    compile 'org.slf4j:slf4j-api:1.7.12'
    runtime 'org.slf4j:slf4j-simple:1.7.12'
}
```
Wait! I have the same dependencies tree! ...So I cannot distinguish between these different cases.
![image](https://cloud.githubusercontent.com/assets/790448/9579612/45aa2056-4ff4-11e5-83cc-943186d6e3ca.png)

#### Case 3: `X` depends on the `main` outputDir, and on some of the other `main` dependies
(I admit, that this is a contrived evil example to make my point)
```gradle
apply plugin: 'java'

repositories {
    mavenCentral()
}

sourceSets {
    x {
        java.srcDir 'src/x/java'
        resources.srcDir 'src/x/resources'
        compileClasspath += files("lib/print.jar")
        compileClasspath += files("$buildDir/classes/main")
        runtimeClasspath += files("$buildDir/classes/main")
    }
}

dependencies {
    compile 'org.slf4j:slf4j-api:1.7.12'
    runtime 'org.slf4j:slf4j-simple:1.7.12'
    xCompile 'org.slf4j:slf4j-api:1.7.12'
}
```

So `main` has compile and runtime dependencies on `slf4j-api` and `slf4j-simple` respectively. And what happens with `x`? It inherits from `main`, but what? `slf4j-api` is a compile dependency, but is not listed under `Compiled`. I have an `inherits main` in the `Provided` dependency, so I could have expected it. But then, `x` then doesn't have any dependency on `slf4j-simple`, so I cannot really understand `x` dependencies:
![image](https://cloud.githubusercontent.com/assets/790448/9579992/bf174f2a-4ff6-11e5-8b08-f1cb27c9d045.png)


Regarding your comment:
> anyway, this inheritance is just for display, NB won't rely on it for classpaths

I fully understand, but I'm trying to use NB as a tool to understand an existing project. I need to build confidence in how NB presents the information.

**Comment by gallardo** [comment]
This gets worse when using even more sourceSets:
```gradle
apply plugin: 'java'

sourceSets {
    x {
        java.srcDir 'src/x/java'
        resources.srcDir 'src/x/resources'
        compileClasspath += files("lib/print.jar")
        runtimeClasspath += files("lib/print.jar")
        compileClasspath += files("$buildDir/classes/main")
        runtimeClasspath += files("$buildDir/classes/main")
    }
    y {
        java.srcDir 'src/y/java'
        resources.srcDir 'src/y/resources'
        compileClasspath += files("lib/print.jar")
        runtimeClasspath += files("lib/print.jar")
        compileClasspath += files("$buildDir/classes/x")
        runtimeClasspath += files("$buildDir/classes/x")
    }
    z {
        java.srcDir 'src/z/java'
        resources.srcDir 'src/z/resources'
        compileClasspath += files("lib/print.jar")
        runtimeClasspath += files("lib/print.jar")

        // XXX: It doesn't even make a difference if I add classes/x or classes/y!
        compileClasspath += files("$buildDir/classes/y")
        runtimeClasspath += files("$buildDir/classes/y")
    }
}
```
I still get my one-node-only Dependencies list:
![image](https://cloud.githubusercontent.com/assets/790448/9580238/8508d6b2-4ff8-11e5-8afd-1c86daa32e81.png)

**Comment by kelemen** [comment]
> When NB signals for x the inherits main, does it mean it uses only its build path, or its build path plus its libraries?

It doesn't mean anything only that *build/classes/main* is on its runtime or compile time classpath. For what matters, NB will simply use `sourceSets.x.compileClasspath` without any filtering or whatever. The whole filtering, "inherits" and whatever is done to show a concise view of the dependencies (it could just list runtimeClasspath and compileClasspath without any processing).

In your last example, the nodes are omitted simply because the only thing they would display is that it inherits a source set (even though, in reality there is no such inheritance).

**Comment by kelemen** [comment]
In general the only correct thing to display would be to simply list both compileClasspath and runtimeClasspath, however in practical cases, it would be needlessly complicated. So, I decided to make the node incorrect in some cases to be clearer in the common case (and the common case covers the vast majority of the projects).

**Comment by gallardo** [comment]
Thanks for your clarifications. I have learnt enough with these threads that I can now resort directly to the sources :smile:
