### ISSUE TITLE
Cannot find tasks that expect or depend on gradlew

### ISSUE THREAD

**Issue by Charlweed** [kelemen/netbeans-gradle-project#237]
Hi,
I read issue #118, but it is still not clear to me why I can successfully execute tasks run from the cli with gradlew, but the custom tasks cannot be accessed in NetBeans. For example, you can clone the minecraft repo "WorldEdit" (https://github.com/sk89q/WorldEdit.git) and follow the instructions in the COMPLING.md, and it will work fine. But with NetBeans, the first custom task, `setupDevWorkspace` is not found. When I right-click, and enter the name in the dialog, I get "Task 'setupDevWorkspace' not found in root project 'worldedit'."
I believe, in the WorldEdit case, that the setupDevWorkspace task is defined in a plugin, which is correctly accessed in a cli execution.

The inability to run the  setup tasks MAY also be leading to to other tasks resolving the gradle property "rootProject.projectDir" to be the NetBeans installation directory, (i.e. C:\Program Files\Netbeans 8\NetBeans 8.0.2) instead of the actual local project dir, and that breaks builds in other ways. I cannot test that, so I will hold off creating another issue for now ;)

**Comment by kelemen** [comment]
I have cloned that repository and executed "setupDevWorkspace" as custom task and it works for me. It is probably not listed because it is a rule and not a task (I'm just assuming this, have not actually checked).

**Comment by kelemen** [comment]
Actually, "setupDevWorkspace" is task of the subproject "worldedit-forge" and the task menu lists only tasks of that particular project, so that is why you don't see it listed on the root project.
