### ISSUE TITLE
Error when Loading and Reloading Projects

### ISSUE THREAD

**Issue by canayozel** [kelemen/netbeans-gradle-project#238]
When loading or reloading, I get URI has an authority component error. The stack trace can be found at
https://gist.github.com/canayozel/4cf755f18a122d55499d#file-gradle-uri-has-authority-issue

Netbeans version 8.0.2.
Plugin version 1.3.7.3.

**Comment by gallardo** [comment]
Can you post your gradle script? Everything points to a wrong classpath. Do you have by chance any dependency in the form of `file://C:/...` instead of `file:///C:/...`? (Notice the extra `/`)

**Comment by canayozel** [comment]
My build.gradle file only contains "apply plugin: 'java'". (SAme result even if the file is empty.)
I checked every file in the project folder in order to find and fix the path. But there is nothing there.

Is there any other project or configuration files I should check ?

**Comment by kelemen** [comment]
How was NetBeans installed into your computer? That is, the error you see means that the ClassLoader of `netbeans-gradle-default-models-*.jar` returns an URL with a authority component.

- Where is the `netbeans-gradle-default-models-*.jar` installed (it is usually in `Users\<User>\AppData\Roaming\NetBeans\<version>\modules\ext`.
- What is written in your `<NetBeans install dir>\etc\netbeans.conf`. In partiuclar, I'm instereseted in the value of the *netbeans_default_userdir* key.
- Is there somekind of password protection which had to be set for NetBeans?

**Comment by kelemen** [comment]
Until this issue is fixed you can workaround the problem by setting *Idea based* for the build script evaluation strategy. See the [related wiki page](https://github.com/kelemen/netbeans-gradle-project/wiki/Build-Script-Parsing) for details.

**Comment by canayozel** [comment]
netbeans_default_userdir  pointed to a network directory starting with \\xx\\yyy when I changed it to directory like C:/NetbeansUserDir it worked.

Thank you.
