### ISSUE TITLE
Single Gradle Project doesn't create dist folder.

### ISSUE THREAD

**Issue by hxdev** [kelemen/netbeans-gradle-project#243]
Hi there!

I'm new with Gradle in Netbean, for normal project, when do the Clean and Build, it'll auto create the dist folder which contains the jar... But when I create the Single Gradle Project and the the Clean and Build, didn't see the dist folder. Is that a bug or with Gradle, we must do something else?

**Comment by WillBDaniels** [comment]
Gradle puts all resulting build items into a 'build' directory, rather than
dist. All resulting jars will be in build/libs.

Hope that helps :)

**Comment by kelemen** [comment]
As @WillBDaniels sad, everything is put inside the build directory by default. You can adjust this in the build script but I see little point in it.

**Comment by hxdev** [comment]
Yes, I've seen the jar files in libs folder but when try to run it, look like it's missing the manifest of main class file.

**Comment by WillBDaniels** [comment]
In order to fix that, add the following code to your build.gradle:

jar {
    manifest {
        attributes 'Main-Class': 'com.test.example.HelloWorld' // <<<<<<
substitute with your main class name, of course.
    }
}

On Sat, Oct 17, 2015 at 6:52 PM, hxdev <notifications@github.com> wrote:

> Yes, I've seen the jar files in libs folder but when try to run it, look
> like it's missing the manifest of main class file.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kelemen/netbeans-gradle-project/issues/243#issuecomment-148964626>
> .
>



-- 
        -William Bryant Daniels
