### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by marccollin** [kelemen/netbeans-gradle-project#244]
Hi

I get some dependenices issue.

A projet can work without problem. I turn off netbeans, open it next day and i get many dependencies issue.

It try to download thing who don't exist like

https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-tools/1.3.0.BUILD-SNAPSHOT/maven-metadata.xml

**Comment by kelemen** [comment]
Does building the project work?

**Comment by marccollin** [comment]
no because it said they miss dependencies

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'server'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve org.springframework.boot:spring-boot-gradle-plugin:1.3.0.BUILD-SNAPSHOT.
     Required by:
         :server:unspecified
      > Could not resolve org.springframework.boot:spring-boot-gradle-plugin:1.3.0.BUILD-SNAPSHOT.
         > Could not parse POM http://repo.spring.io/snapshot/org/springframework/boot/spring-boot-gradle-plugin/1.3.0.BUILD-SNAPSHOT/spring-boot-gradle-plugin-1.3.0.BUILD-20151019.104149-707.pom
            > Could not resolve org.springframework.boot:spring-boot-tools:1.3.0.BUILD-SNAPSHOT.
               > Could not resolve org.springframework.boot:spring-boot-tools:1.3.0.BUILD-SNAPSHOT.
                  > Could not parse POM http://repo.spring.io/snapshot/org/springframework/boot/spring-boot-tools/1.3.0.BUILD-SNAPSHOT/spring-boot-tools-1.3.0.BUILD-20151019.104149-708.pom
                     > Could not resolve org.springframework.boot:spring-boot-parent:1.3.0.BUILD-SNAPSHOT.
                        > Could not resolve org.springframework.boot:spring-boot-parent:1.3.0.BUILD-SNAPSHOT.
                           > Could not parse POM http://repo.spring.io/snapshot/org/springframework/boot/spring-boot-parent/1.3.0.BUILD-SNAPSHOT/spring-boot-parent-1.3.0.BUILD-20151019.104149-707.pom
                              > Could not resolve org.springframework.boot:spring-boot-dependencies:1.3.0.BUILD-SNAPSHOT.
                                 > Could not resolve org.springframework.boot:spring-boot-dependencies:1.3.0.BUILD-SNAPSHOT.
                                    > Could not parse POM http://repo.spring.io/snapshot/org/springframework/boot/spring-boot-dependencies/1.3.0.BUILD-SNAPSHOT/spring-boot-dependencies-1.3.0.BUILD-20151019.104149-708.pom
                                       > Could not find org.springframework:spring-framework-bom:4.2.2.RELEASE.
                                         Searched in the following locations:
                                             http://repo.spring.io/snapshot/org/springframework/spring-framework-bom/4.2.2.RELEASE/spring-framework-bom-4.2.2.RELEASE.pom
                                             http://repo.spring.io/snapshot/org/springframework/spring-framework-bom/4.2.2.RELEASE/spring-framework-bom-4.2.2.RELEASE.jar
                                             http://repo.spring.io/milestone/org/springframework/spring-framework-bom/4.2.2.RELEASE/spring-framework-bom-4.2.2.RELEASE.pom
                                             http://repo.spring.io/milestone/org/springframework/spring-framework-bom/4.2.2.RELEASE/spring-framework-bom-4.2.2.RELEASE.jar

* Try:

**Comment by kelemen** [comment]
It is most likely a Gradle issue then (or something with connection like proxy issues). Anyway, I would first try deleting Gradle's cache (in ~/.gradle/caches).

**Comment by marccollin** [comment]
if i can click on the link and see the file, don't think that could be a proxy issue.

i deleted caches, get same result.

is there a way to said to gradle don't check on the web dependencies?

**Comment by kelemen** [comment]
Does it work from the command line? If so, then it is likely to be a proxy issue (by the way, do you have non-proxy hosts?).

**Comment by marccollin** [comment]
seem to get same issue in command line.

```
configurations.all {
    resolutionStrategy.cacheDynamicVersionsFor 999, 'hours'
}

configurations.all {
    resolutionStrategy.cacheChangingModulesFor 999, 'hours'
}
```

don't seem to block cache to see dependency on the web.

**Comment by kelemen** [comment]
If it does not work from the command line, then you should try reporting this issue on the Gradle forums, they could probably help you better with this issue.
