### ISSUE TITLE
I get a SIGSEGV with my Gradle Project on Linux, but Windows is fine

### ISSUE THREAD

**Issue by elect86** [kelemen/netbeans-gradle-project#246]
I started recently using Gradle, on my Netbeans I installed the corresponding plugin, I followed a couple of tutorials with sample projects. Now I decided to implement it in a small project of mine.

You can find it [here](https://github.com/elect86/jgliGradle), it is a small project to load dds, dxgi and ktx texture in java. It is a port of the original [gli](http://gli.g-truc.net/).

I have a [Main class](https://github.com/elect86/jgli/blob/master/src/main/java/test/Main.java) that I use as a quick and dirty test. Launching from Netbeans, on windows it runs fine, on Linux it crashes.

    Executing: gradle :run
    Arguments: [-PmainClass=test.Main, -c, /home/elect/NetBeansProjects/jgli/settings.gradle]
    
    :compileJava
    :processResources UP-TO-DATE
    :classes
    :run
    #
    # A fatal error has been detected by the Java Runtime Environment:
    #
    #  SIGSEGV (0xb) at pc=0x0000000000002546, pid=14243, tid=140554612987648
    #
    # JRE version: OpenJDK Runtime Environment (8.0_45-b14) (build 1.8.0_45-internal-b14)
    # Java VM: OpenJDK 64-Bit Server VM (25.45-b02 mixed mode linux-amd64 compressed oops)
    # Problematic frame:
    # C  0x0000000000002546
    #
    # Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
    #
    # An error report file with more information is saved as:
    # /home/elect/NetBeansProjects/jgli/hs_err_pid14243.log
    #
    # If you would like to submit a bug report, please visit:
    #   http://bugreport.java.com/bugreport/crash.jsp
    #
    :run FAILED
    
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Execution failed for task ':run'.
    > Process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/java'' finished with non-zero exit value 134
    
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    
    BUILD FAILED
    
    Total time: 19.144 secs

You can find the log [here](https://gist.github.com/elect86/1fc7135fe48e9f7a4c9a)

 This class implements `GLEventListener` and `KeyListener` from the jogamp library.

And this is my [`build.gradle`](https://github.com/elect86/jgli/blob/master/build.gradle)

How can I solve it?

**Comment by kelemen** [comment]
Given your stacktrace, it is definitely not a bug in NetBeans/this plugin nor in Gradle. I can only guess what it can be: For example, a driver issue or maybe somehow you corrupted the memory with some *unsafe* operation or possibly in JOGL. If you don't think its your or the driver's fault, you should report it to the JOGL team along with your code (the build script is not relevant).

**Comment by elect86** [comment]
Ok, thanks
