### ISSUE TITLE
Changing dependencies of project requires clear of the cache

### ISSUE THREAD

**Issue by kravemir** [kelemen/netbeans-gradle-project#247]
I've created Gradle Root Project and SubProject using create new project wizards. However, whenever I add any maven dependency nothing happens.

After some investigation I've found, that I need to clear NetBeans cache (http://stackoverflow.com/questions/8760333/netbeans-error-package-org-does-not-exist).

This approach is unacceptable as normal behaviour, because it's very time consuming.

**Comment by kelemen** [comment]
You shouldn't remove the NetBeans cache that is only a very rare bug in NB (it was years ago since I last came across that bug). The only thing you must do is to reload the project to parse the build script again (right click on project node and reload project).
