### ISSUE TITLE
can't inject my NodeFactory into Gradle project

### ISSUE THREAD

**Issue by raydac** [kelemen/netbeans-gradle-project#250]
Hello, thank you very much for your very useful plugin
I have some question, in my [NBMindMap plugin](https://github.com/raydac/netbeans-mmd-plugin), I am injecting NodeFactory into projects to show virtual folder called "Knowledge", it works well with Jav netBeans project but doesn't work with Gradle projects, I use registration through 
```
@NodeFactory.Registration (projectType = {
 ...
"org-netbeans-gradle-project",
 ...
}, position=10000)
```
may be I am wrong in prohect type?

**Comment by kelemen** [comment]
This support is not in the latest release, you will have to build the plugin from the sources manually for this to work. Also, the for the project type you have to use the constant defined in [GradleProjectIDs.ODULE_NAME](https://github.com/kelemen/netbeans-gradle-project/blob/master/netbeans-gradle-plugin/src/main/java/org/netbeans/gradle/project/api/entry/GradleProjectIDs.java#L16) which is `org.netbeans.gradle.project`. I will probably have a new release in a few weeks.

**Comment by kelemen** [comment]
Also, the current nodes do not use this annotation, so the position value is meaningless for them, your node will always come before those nodes.

**Comment by kelemen** [comment]
I assume your issue is solved, so I will close this. Please, reopen this, if you believe otherwise.
