### ISSUE TITLE
Saving new custom task from the "run custom task" dialog drop all existing custom tasks

### ISSUE THREAD

**Issue by eskatos** [kelemen/netbeans-gradle-project#251]
One can run and save custom tasks on a project node right-click menu.

__Expected behavior__

When saving a custom task declaration for later reuse from the "run custom task" dialog, it should be added to the list of existing custom tasks.

__Observed behavior__

Netbeans 8.1
Gradle Support 1.3.7.2

When saving a custom task declaration for later reuse from the "run custom task" dialog, all existing custom task(s) are removed and replaced with the new one.

__Workaround__

Open project properties, then `Custom Tasks` and edit them here.

**Comment by MT-AKelemen** [comment]
This definitely seems to be a bug. You mean, only from the run custom dialog, don't you? I mean, if you go to the project properties, you should be able to edit the list properly.

**Comment by kelemen** [comment]
This definitely seems to be a bug. You mean, only from the run custom dialog, don't you? I mean, if you go to the project properties, you should be able to edit the list properly.

**Comment by eskatos** [comment]
> You mean, only from the run custom dialog, don't you?

Exactly.

> if you go to the project properties, you should be able to edit the list properly.

Right, thanks. I updated the issue.

**Comment by kelemen** [comment]
Should be fixed in master, though the master branch does not work with NB 8.1. You can locally merge NetBeans81 and master for now until after I have finished another feature, I'm working on.

**Comment by eskatos** [comment]
Great thanks!
