### ISSUE TITLE
Netbeans warns that the Gradle Support plugin is self signed

### ISSUE THREAD

**Issue by tengwar** [kelemen/netbeans-gradle-project#252]
Netbeans 8.1 warns me that the Gradle Support plugin is self signed and asks if I want to continue installing it. Is this how it should be? Is this a MITM?

**Comment by kelemen** [comment]
Yes, it is self signed. If you are worried this is my public key:

    Certificate:
        Data:
            Version: 3 (0x2)
            Serial Number: 1810841236 (0x6bef3e94)
            Signature Algorithm: dsaWithSHA1
            Issuer: C=HU, ST=Unknown, L=Unknown, O=Unknown, OU=Unknown, CN=Attila Kelemen
            Validity
                Not Before: Sep  1 12:10:12 2012 GMT
                Not After : Aug 31 12:10:12 2017 GMT
            Subject: C=HU, ST=Unknown, L=Unknown, O=Unknown, OU=Unknown, CN=Attila Kelemen
            Subject Public Key Info:
                Public Key Algorithm: dsaEncryption
                DSA Public Key:
                    pub: 
                        39:8c:27:a5:eb:e9:7e:d3:05:e8:18:70:18:d6:ba:
                        2b:4b:4a:59:c0:5c:e6:2f:35:ba:be:19:b4:4f:af:
                        65:fd:00:00:67:d8:04:b1:77:d3:26:3f:78:43:fb:
                        dd:35:1d:86:eb:16:5e:a3:dd:c9:db:05:30:9d:8d:
                        b0:c7:b3:38:30:7b:dd:70:c0:cb:d6:8a:c9:e0:8b:
                        eb:dc:2e:ef:9b:b0:0d:c5:77:ba:8c:96:08:61:1e:
                        37:26:b3:90:c3:11:4a:4f:02:a2:5c:84:98:dc:dd:
                        38:98:c1:6c:c5:94:ca:47:b9:0c:a0:67:07:30:f0:
                        e3:96:bb:70:68:08:ad:a5
                    P:   
                        00:fd:7f:53:81:1d:75:12:29:52:df:4a:9c:2e:ec:
                        e4:e7:f6:11:b7:52:3c:ef:44:00:c3:1e:3f:80:b6:
                        51:26:69:45:5d:40:22:51:fb:59:3d:8d:58:fa:bf:
                        c5:f5:ba:30:f6:cb:9b:55:6c:d7:81:3b:80:1d:34:
                        6f:f2:66:60:b7:6b:99:50:a5:a4:9f:9f:e8:04:7b:
                        10:22:c2:4f:bb:a9:d7:fe:b7:c6:1b:f8:3b:57:e7:
                        c6:a8:a6:15:0f:04:fb:83:f6:d3:c5:1e:c3:02:35:
                        54:13:5a:16:91:32:f6:75:f3:ae:2b:61:d7:2a:ef:
                        f2:22:03:19:9d:d1:48:01:c7
                    Q:   
                        00:97:60:50:8f:15:23:0b:cc:b2:92:b9:82:a2:eb:
                        84:0b:f0:58:1c:f5
                    G:   
                        00:f7:e1:a0:85:d6:9b:3d:de:cb:bc:ab:5c:36:b8:
                        57:b9:79:94:af:bb:fa:3a:ea:82:f9:57:4c:0b:3d:
                        07:82:67:51:59:57:8e:ba:d4:59:4f:e6:71:07:10:
                        81:80:b4:49:16:71:23:e8:4c:28:16:13:b7:cf:09:
                        32:8c:c8:a6:e1:3c:16:7a:8b:54:7c:8d:28:e0:a3:
                        ae:1e:2b:b3:a6:75:91:6e:a3:7f:0b:fa:21:35:62:
                        f1:fb:62:7a:01:24:3b:cc:a4:f1:be:a8:51:90:89:
                        a8:83:df:e1:5a:e5:9f:06:92:8b:66:5e:80:7b:55:
                        25:64:01:4c:3b:fe:cf:49:2a
            X509v3 extensions:
                X509v3 Subject Key Identifier: 
                    F0:DA:7B:70:7E:74:17:3C:A7:E0:E4:B9:D5:25:F8:6D:72:27:97:1B
        Signature Algorithm: dsaWithSHA1
            30:2c:02:14:63:bc:c0:30:cf:53:10:0f:0b:9e:cb:6a:b1:66:
            92:90:6c:36:e1:4a:02:14:44:b7:9a:14:78:b0:41:1d:8b:81:
            06:d6:c3:cb:24:1e:0e:22:fd:77
