### ISSUE TITLE
Ambiguity of "Reload Project" and "Refresh project node" in context menu

### ISSUE THREAD

**Issue by xtracoder** [kelemen/netbeans-gradle-project#259]
I could not find if there is some 'user guide' for this plugin, therefore trying to use it in trial-and-error manner.

Since plugin does not automatically apply changes done to build.gradle, I rather regularly have to invoke "Reload Project" and "Refresh project node" to apply changes (for example in project dependencies). Each time I do this - I invoke both of them because I do not see semantical difference  between Reload and Refresh and not sure which of them is missing what functionality.

May it be more user-friendly to leave only one entry in context menu, which always does complete reload/refresh/whatever-needed to apply all changes?

PS: I did not notice large delay during load of the project (as mentioned at the end of https://github.com/kelemen/netbeans-gradle-project). Gradle mentions many performance improvements in their what's news - probably now it's OK to refresh project automatically with modern versions of Gradle? At least make it optional - and let the user decide what is more convenient.

**Comment by kelemen** [comment]
"Refresh project node" is almost always pointless. This is what these actions do:

- *Refresh project node*: Simply recreates all the nodes in the project view. It won't reload the project model from the build script. The intent of this action is to let you refresh the nodes if the nodes failed to refresh themselves (they should never fail). So - assuming no bug - 
- *Reload project*: Reloads the project information from the build script. This will lazily refresh the project nodes as well (unless, there is a bug, it should refresh the project node properly).

Yes, nowadays Gradle is *much* faster. I guess an optional refresh automatically would be fine. Though I don't know what files you are using from the build script, so I could only monitor the *build.gradle* and the *settings.gradle* files.

**Comment by xtracoder** [comment]
"build.gradle and the settings.gradle" would be ok, though in multi-module project - changing 'build.gradle' of parent should also reload all children (I guess).

BTW, what will "Reload project" on some parent module do? I think it should cause reload of the children too.

**Comment by kelemen** [comment]
In theory, reload project only reloads that particulary selected project. However, this is not the case in practice, because Gradle evaluates every project in the multi-project build. That is, currently, regardless of what subproject you reload, all projects in that multi-project build gets reloaded.

**Comment by xtracoder** [comment]
"_Gradle evaluates every project in the multi-project build_" - this is not always correct. 

With `org.gradle.configureondemand=true` and without `allproject {}` or `subprojects{}` in build files (can be replaced by `gradle.beforeProject { project -> ... }`) - gradle evaluates only relevant projects plus root project and this greatly speeds up building of individual sub-modules (when total count is around 350).

This is the setup I have in my projects.

PS: you may take a look [here](https://discuss.gradle.org/t/parent-project-is-not-evaluated-with-configuration-on-demand-and-partial-build/13925) for example.

**Comment by kelemen** [comment]
I know about that property but it has no effect when evaluating the projects for model loading.

**Comment by kelemen** [comment]
I have removed the "Refresh project node" item, since it was not useful in practice.
