### ISSUE TITLE
Problem while building project with Gradle

### ISSUE THREAD

**Issue by santteegt** [kelemen/netbeans-gradle-project#260]
Hi, 

I'm having an issue when trying to build the project with Graddle. The dependencies on repositories https://raw.githubusercontent.com/whispersystems/maven/master/preferencefragment/releases/ and https://raw.github.com/whispersystems/maven/master/shortcutbadger/releases/ are not reachable. I have installed the Android SDK and Build Tools v 22.x.x . How can I solve this ?

Main error: peer not authenticated

Thanks

**Comment by wadechandler** [comment]
When you go to those URLs without being logged into github what do you get in the browser? I get a 400. So, you have to be able to tell Gradle your user ID and password. That is what your error message is twlling you. This is a Gradle issue, and not related to the plugin, and certainly not a bug in either as far as can be understood by your information. You need to be able to build your Gradle project from the command line before anything else. I suggest reading the manual on repository configuration ... https://docs.gradle.org/current/userguide/dependency_management.html

**Comment by santteegt** [comment]
yeah, I read that, but what is the username/password to access those repos ?
