### ISSUE TITLE
Usability - missing kb shortcuts in context menu

### ISSUE THREAD

**Issue by xtracoder** [kelemen/netbeans-gradle-project#263]
Currently context menu in Project explorer has no keyboard shortcuts assigned - and this is really inconvenient. I've done some fixes in my fork. Please merge as needed - [commit](https://github.com/xtracoder/netbeans-gradle-project/commit/74863fbb443744b14f4bb3cb379172f8ef054a07)

1. Keyboard shortcuts add
2. Action "Set as Main Project" added - (NB has default action in context menu over blank space, but selecting correct sub-projects from list 100+ elements is really not handy)

**Comment by kelemen** [comment]
I will review and merge these changes later.

**Comment by kelemen** [comment]
I have completely forgotten this. Merged the changes now but made some adjustments to it.
