### ISSUE TITLE
Support for NBM hot-reloading

### ISSUE THREAD

**Issue by xtracoder** [kelemen/netbeans-gradle-project#264]
I'm not sure how you are testing this plugin, but the only way I know to switch to updated version of NBM (the changes not supported by 'apply code changes') is "uninstalling plugin" -> restarting IDE -> "reinstalling plugin". This is really time consuming.

MAVEN's support for NBM adds following actions into project's context menu:
- Reload in Target Platform
- Install/Reload in Development IDE

I guess something similar has sense to be supported in Gradle plugin, though I'm not sure how Gradle project can be identified as NBM pluging. 

You may find implementation for MAVEN in [sources of NetBeans](https://netbeans.org/community/sources/) :
apisupport.ant\src\org\netbeans\modules\apisupport\project\ui\ line:876
maven.apisupport\src\org\netbeans\modules\maven\apisupport\ line:115

**Comment by kelemen** [comment]
I use the "debug" or the "run" command, reload in target platform is somewhat unsafe (if I happen to make a change which breaks NB). See the [wiki](https://github.com/kelemen/netbeans-gradle-project/wiki/Development) for how to setup running and debugging.

Also, this is something which should be put in Radim's NBM plugin (I'm using an old version of his plugin in buildSrc as it was not released back then and I never felt the need to move to the "official" plugin).
