### ISSUE TITLE
Unable to identify exception that occurs as a debugging session terminates. (... and 4 related issues)

### ISSUE THREAD

**Issue by david-hall** [kelemen/netbeans-gradle-project#267]
I'm running vesion 1.3.8 of the Gradle Netbeans plugin in NetBeans version 8.0.2 (Build 201411181905). I don't know if these issues are fixed in version 1.3.8.1. because it's not available yet when I check for plugin updates. I'll give it a try as soon as it's published to the normal update channels. With that background, here's a description of the main issue. Several related issues are listed at the end of this description.

When running my application in the NB debugger, I simply invoke the app and then close it normally. The output window shows:

    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Build cancelled.
    
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    
    BUILD FAILED

Re-running it again with the --info and --stacktrace parameters does not identify the exception, but generates the following message when the debug session ends:

    :debug (Thread[Daemon worker,5,main]) completed. Took 22.077 secs.
    :platform:debug (Thread[Daemon worker,5,main]) started.
    :platform:debug
    Executing task ':platform:debug' (up-to-date check took 0.0 secs) due to:
    Task has not declared any outputs.
    Cannot execute debug because the project does not have classes or source sets.
    :platform:debug (Thread[Daemon worker,5,main]) completed. Took 0.01 secs.
    :jar (Thread[Daemon worker,5,main]) started.
    :jar
    HandleCancel processing Build{id=3ce70189-0321-48b9-baf3-27d245b6dcda.1, currentDir=C:\Program Files\NetBeans 8.0.2}
    Executing task ':jar' (up-to-date check took 0.418 secs) due to:
    Input file C:\Users\DHall\Documents\GitHub\vzome-desktop\build\resources\main\build.properties has changed.
    :jar (Thread[Daemon worker,5,main]) completed. Took 2.527 secs.
    
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Build cancelled.
    
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.
    
    BUILD FAILED

I don't know why the jar task or any subproject task is run after the debug session. That's a separate issue, but for now, I specifically disabled the jar task by adding -x jar to the gradle parameters. I also don't want :platform:debug task to run. Somehow disabling the jar task also disabled :platform:debug, which is nice, but unexpected. Again, that's a separate issue, so now I'm left with this:

    HandleCancel processing Build{id=d5175122-c5c8-4e18-93d7-6b7f0837c1f3.1, currentDir=C:\Program Files\NetBeans 8.0.2}
    :debug (Thread[Daemon worker Thread 3,5,main]) completed. Took 19.505 secs.
    
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Build cancelled.
    
    * Try:
    Run with --debug option to get more log output.

Note that this time, the HandleCancel occurs before the debug task completes whereas originally it happened after the jar task started, so now I try running with --debug instead of --info and I get a lot messages in the of output window, but the application never starts this time, which is yet another separate issue. The last few lines are:

    14:15:35.873 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTING
    14:15:35.876 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Waiting until process started: command 'C:\Program Files\Java\jdk1.8.0_74\bin\java.exe'.
    14:15:35.931 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTED
    14:15:36.004 [DEBUG] [org.gradle.process.internal.ExecHandleRunner] waiting until streams are handled...
    14:15:36.005 [INFO] [org.gradle.process.internal.DefaultExecHandle] Successfully started process 'command 'C:\Program Files\Java\jdk1.8.0_74\bin\java.exe''
    14:15:36.248 [QUIET] [system.out] Listening for transport dt_socket at address: 5005

At that point, all I can do is forcibly cancel the execution of the debug task and remove the --debug parameter, which brings me to the issue at hand. I can't find a way to identify, and ideally fix, the exception that is being reported when the debug session ends. My only clue is that it seems to be related to HandleCancel, but I'm not even sure of that.

In addition to that, I have a few other separate issues that have come up during this process. Since the explanation for them is all woven through the narative above, I have listed then here rather than submitting them individually to be tracked as separate issues. If it's helpful, they could be tracked as distinct issues which simply reference this issue for their description.

1) The jar task should not be run after a debug session. 
2) Subproject tasks (specifically including debug) should not be run after the debug task in the parent projects.
3) Disabling the jar task by adding -x jar to the list of parameters somehow also disables tasks in subproject (specifically task :platform:debug). Although I did want to disable all subproject tasks, I don't know why disabling the jar task in the root project should have that effect.
4) Running the debug task with the --debug parameter doesn't ever start the application. The debug task has to be forcibly stopped.

Thanks for looking into these.

**Comment by kelemen** [comment]
Since, NB 8.1 is not backward compatible with previous versions of NB, I have separate versions for them *1.3.8* is for *NB 7.3-8.0* while *1.3.8.1* is for *NB 8.1*. That is, *1.3.8.1* will never be released for *NB 8.0*.

For every action, NB will simply run a Gradle command. For debugging, the only extra thing it does, is that it will try to attach to the debugee by default. Actually, these are the two kinds of way NB can work when debugging:

1. Debugger attaches to the debugee: NB will simply look for the text *Listening for transport dt_socket at address* on the standard output. (later I will describe why it doesn't work for you)
2. Debuggee attaches to NB (debugger): NB will pass the `debuggerJpdaPort` project property and expects the project to configure its run task so that it will attach to the debugger on this port. [nb-init-script.gradle](https://github.com/kelemen/netbeans-gradle-project/blob/v1.3.8/netbeans-gradle-plugin/src/main/resources/org/netbeans/gradle/project/resources/nb-init-script.gradle) will try to configure your `JavaExec` task based on this property but you could do that manually as well. This probably would work for you, if you were to use the default configuration for the debug tasks (you can configure this in global settings or in the project properties, see the [wiki](https://github.com/kelemen/netbeans-gradle-project/wiki/Debug-Settings) for details).

First of all, I don't plan on maintaining pre 8.1 versions of NB (i.e., no new releases) but luckly these problems are very easy to fix and you can build the plugin yourself for earlier versions (it builds out of the box). This is what should be done:

- [GradleJavaBuiltInCommands](https://github.com/kelemen/netbeans-gradle-project/blob/v1.3.8/netbeans-gradle-plugin/src/main/java/org/netbeans/gradle/project/java/tasks/GradleJavaBuiltInCommands.java) has the tasks to run for any Java specific commands. As you can see there tasks like `debug` are specified simply as that (I left these this way because noone complained about them yet and I didn't want to change the behaviour if noone cares).what should be there instead is something like `projectTask("debug")`. This would solve your problem of additional tasks being run.
- The never attaching debugger problem is because the plugin is looking for the string mentioned above in the beginning of the line (which is not so in your case). The [DebugTextListener](https://github.com/kelemen/netbeans-gradle-project/blob/v1.3.8/netbeans-gradle-plugin/src/main/java/org/netbeans/gradle/project/output/DebugTextListener.java) must be fixed for this or you can just configure NB to let the debuggee attach to the debugger.

**Comment by david-hall** [comment]
I didn't realize that a newer version of NetBeans had been released. I'll install it tonight and see if the latest version of this plugin behaves correctly with my existing projects. If not, I'll check out some of your suggestions and let you know how they work out. Thanks for the explanations.

**Comment by kelemen** [comment]
That version will have to same behaviour as well.

**Comment by david-hall** [comment]
I upgraded NetBeans to version 8.1 and installed the latest version of the plugin. It behaves the same, just as you said it would, but at least now I'm using a supported version of the plugin. Is the change to GradleJavaBuiltInCommands that you described something you would consider immplementing? If so, I'd be happy to test it for you. 

In the mean time, in case anyone else is having the same problem, I have worked around it by specifically excluding the unwanted jar task and the run task of each subproject folder when the run task is invoked. Specifically, I manually added the following parameters to the plugin's "debug" command: 

    -x jar -x :platform:run -x :platform:windows:run

Note that even though there is no build.gradle in the platform folder, there is one in platform\windows. I found that I had to specifically exclude the platform folder as if it were an actual subproject folder.

It's not too much hassle in my case since I only have one subproject, but it's still not a clean solution since without this manual reconfiguration, executing the "run" task from the command line behaves differently than executing "run" via the debug command of the plugin. This work-around would be messy to maintain if there were more than just a few subprojects.

Thanks.

**Comment by MT-AKelemen** [comment]
I can do this sometime this week.

Instead of writing excludes, it would be better to simply replace *run* with *${project}:run*.

If you include "platform:windows" in the *settings.gradle*, you will implictly include "platform" as well. I assume that you apply plugins via the `subprojects` (or `allprojects`) method and so add the `run` task to "platform" as well.

Execution does not really behave in a different way than the command line. It works as if you "cd"-d into the project directory and executec `gradle run` (which implies executing `run` in every subproject as well).

**Comment by kelemen** [comment]
I can do this sometime this week.

Instead of writing excludes, it would be better to simply replace run with ${project}:run.

If you include "platform:windows" in the settings.gradle, you will implictly include "platform" as well. I assume that you apply plugins via the subprojects (or allprojects) method and so add the run task to "platform" as well.

Execution does not really behave in a different way than the command line. It works as if you "cd"-d into the project directory and executec gradle run (which implies executing run in every subproject as well).

**Comment by david-hall** [comment]
Thanks for making this change. Let me know how and when I can test it for you. 

In the mean time, as you suggested, when I change the task from "run" to "${project}:run", I no longer need to specifically exclude the jar task or any subproject tasks. That's a lot cleaner than my original approach, but I still look forward to having that be the default behavior of the plugin. 

Also, not that it will matter once you make the change to the plugin, but I wanted to explain what I mean about the difference in behavior when gradle is executed from the plugin vs. being run from the command line in case it helps bring any other obscure problem to light.

When I execute 'gradlew run' from the command line in the project directory, none of the unexpected tasks, including subproject tasks are executed as shown in the last line here:

    C:\Users\DHall\Documents\GitHub\vzome-desktop [master]> ./gradlew run --info
    Starting Build
    Settings evaluated using settings file 'C:\Users\DHall\Documents\GitHub\vzome-desktop\settings.gradle'.
    Projects loaded. Root project using build file 'C:\Users\DHall\Documents\GitHub\vzome-desktop\build.gradle'.
    Included projects: [root project 'vzome-desktop', project ':platform', project ':platform:windows']
    Evaluating root project 'vzome-desktop' using build file 'C:\Users\DHall\Documents\GitHub\vzome-desktop\build.gradle'.
    recorded build properties
    Evaluating project ':platform' using empty build file.
    Evaluating project ':platform:windows' using build file 'C:\Users\DHall\Documents\GitHub\vzome-desktop\platform\windows\build.gradle'.
    All projects evaluated.
    Selected primary task 'run' from project :
    Tasks to be executed: [task ':compileJava', task ':recordBuildProperties', task ':processResources', task ':classes', task ':run']
    ...

but when I run it with the plugin using the default (inherited) configuration, for some reason it includes the jar task and the subprojects' run task and a few other tasks as shown in the last line below:

    JPDA Address: DHallW7x64:53674
    Port: 53674
    Executing: gradle run --info
    Arguments: [-PdebuggedTaskName=:run, -PdebuggerJpdaPort=53674, -c, C:\Users\DHall\Documents\GitHub\vzome-desktop\settings.gradle]
    
    The client will now receive all logging from the daemon (pid: 4704). The daemon log file: C:\Users\DHall\.gradle\daemon\2.2.1\daemon-4704.out.log
    Executing build with daemon context: DefaultDaemonContext[uid=1ba84ecb-443c-478c-8248-d3b7cb9eb62e,javaHome=C:\Program Files\Java\jdk1.8.0_74,daemonRegistryDir=C:\Users\DHall\.gradle\daemon,pid=4704,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=windows-1252,-Duser.country=US,-Duser.language=en,-Duser.variant]
    Starting Build
    Settings evaluated using settings file 'C:\Users\DHall\Documents\GitHub\vzome-desktop\settings.gradle'.
    Projects loaded. Root project using build file 'C:\Users\DHall\Documents\GitHub\vzome-desktop\build.gradle'.
    Included projects: [root project 'vzome-desktop', project ':platform', project ':platform:windows']
    Evaluating root project 'vzome-desktop' using build file 'C:\Users\DHall\Documents\GitHub\vzome-desktop\build.gradle'.
    recorded build properties
    Evaluating project ':platform' using empty build file.
    Evaluating project ':platform:windows' using build file 'C:\Users\DHall\Documents\GitHub\vzome-desktop\platform\windows\build.gradle'.
    All projects evaluated.
    Selected primary task 'run' from project :
    Tasks to be executed: [task ':compileJava', task ':recordBuildProperties', task ':processResources', task ':classes', task ':run', task ':platform:run', task ':jar', task ':platform:windows:compileJava', task ':platform:windows:processResources', task ':platform:windows:classes', task ':platform:windows:run']
    ...

yet if I invoke gradle from the command line with exacly the same parameters as as the plugin claims to be using, the extra tasks are not included as you can see on the last line below:

    C:\Users\DHall\Documents\GitHub\vzome-desktop [master]> ./gradlew run --info -PdebuggedTaskName=:run -PdebuggerJpdaPort=53674 -c C:\Users\DHall\Documents\GitHub\vzome-desktop\settings.gradle
    Starting Build
    Settings evaluated using settings file 'C:\Users\DHall\Documents\GitHub\vzome-desktop\settings.gradle'.
    Projects loaded. Root project using build file 'C:\Users\DHall\Documents\GitHub\vzome-desktop\build.gradle'.
    Included projects: [root project 'vzome-desktop', project ':platform', project ':platform:windows']
    Evaluating root project 'vzome-desktop' using build file 'C:\Users\DHall\Documents\GitHub\vzome-desktop\build.gradle'.
    recorded build properties
    Evaluating project ':platform' using empty build file.
    Evaluating project ':platform:windows' using build file 'C:\Users\DHall\Documents\GitHub\vzome-desktop\platform\windows\build.gradle'.
    All projects evaluated.
    Selected primary task 'run' from project :
    Tasks to be executed: [task ':compileJava', task ':recordBuildProperties', task ':processResources', task ':classes', task ':run']
    ...


Hope that helps clarify my point about the command line and the plugin behaving differently in this particular case.

Thanks again,
David

**Comment by kelemen** [comment]
The difference is that you don't have `run` task added to your projects except for the root. However, the plugin will (dynamically and temporarily) add a `run` task for each Java project. That is, the plugin will apply [nb-init-script.gradle](https://github.com/kelemen/netbeans-gradle-project/blob/v1.3.8.1/netbeans-gradle-plugin/src/main/resources/org/netbeans/gradle/project/resources/nb-init-script.gradle) to your project before running any tasks.

**Comment by david-hall** [comment]
That makes sense. That's the part I was not understanding. Even so, I'm looking forward to trying your fix whenever it's available.

Thanks again.

**Comment by kelemen** [comment]
This should be fixed in master, you can build the plugin from the sources (it should build out of the box). Reopen if something is wrong.

**Comment by david-hall** [comment]
Thanks for making these changes. I was able to download and build it, but can't figure out how to upgrade it in NetBeans to test it. 

I successfully build the plugin from the command line in the project's root folder using the command ./gradlew assemble. There were a few "Cookie rejected..." warnings as the build process attempted to download all of the dependencies and then a few more warnings which I've listed here:

    jdk7Compiler property is missing and not compiling with Java 1.7. Using 1.8
    warning: [options] bootstrap class path not set in conjunction with -source 1.7
    warning: Supported source version 'RELEASE_6' from annotation processor 'org.netbeans.modules.openide.util.NbBundleProcessor' less than -source '1.7'
    warning: Supported source version 'RELEASE_6' from annotation processor 'org.netbeans.modules.gsf.testrunner.CoreManagerProcessor' less than -source '1.7'
    warning: No processor claimed any of these annotations: javax.annotation.Nonnull,javax.annotation.Nullable,org.netbeans.gradle.project.api.nodes.ManualRefreshedNodes,org.netbeans.gradle.project.api.nodes.GradleProjectAction,javax.annotation.CheckForNull,org.netbeans.api.annotations.common.CheckForNull
    warning: No processor claimed any of these annotations: javax.annotation.Generated
                                                                                                                                                                                  
Other than those few warnings, it seems to have built OK and re-executing ./gradlew assemble shows everything UP-TO-DATE without trying to download or recompile anything, so I guess it's all OK.

After that point, I wasn't sure exactly where to find the new plugin file (or files?) or how to tell NetBeans to use the newer version of this plugin. After backing up the original plugin jar file. I tried simply replacing the old jar file with the new one with the following command from the project's root folder:

    copy .\netbeans-gradle-project-master\netbeans-gradle-plugin\build\libs\netbeans-gradle-plugin-1.3.8.2.jar %AppData%\NetBeans\8.1\modules\org-netbeans-gradle-project.jar

At that point I tried starting NetBeans. It logged a few ClassNotFound exceptions. I did not make not of the specific details, but it no longer loaded my last (gradle) project. I closed NetBeans, restored the original plugin jar file, and restarted netBeans which then loaded my last projects correctly, so at this point, I'm back to running with version 1.3.8.1 of the plugin and decided I'd better ask for specific instructions for building this version of the plugin and for upgrading it within NetBeans. 

Can you help me with specific instructions for this last step?

**Comment by kelemen** [comment]
The warnings can be ignored. Though, if you build the plugin with Java 8, you cannot load projects using Java 7 or prior versions (you have to use 8 for them). If you want to fix this, you have to define the path to the appropriate javac in the *jdk5Compiler* and *jdk7Compiler* properties (preferrably defined in the global *gradle.properties*). Regardless, this is not necessarily important for you.

Anyway, the nbm to install should be in *netbeans-gradle-plugin/build/nbm* after you build the plugin.

**Comment by david-hall** [comment]
That was the last part I was missing. The new version seems to be working as expected now, with no need to override the default configuration. It also works correctly now if I manually add the *--debug* parameter. 

Initially there was no *netbeans-gradle-plugin/build/nbm* folder and it wasn't clear how to generate it. For future reference in case anyone else is trying to build this project and install it, I found that the plugin is generated by running **./gradlew nbm** from the command line. After that, the plugin is installed in NetBeans by selecting *Tools | Plugins | Downloaded | Add Plugins...* then selecting *netbeans-gradle-plugin/build/nbmorg-netbeans-gradle-project.nbm* and restarting NetBeans.

For now, I'll live with the limit on not building java projects prior to Java 8, but I'll plan to replace it with your "official" release 1.3.8.2 whenever it's available through the normal distribution/upgrade channels.

Thanks again for fixing this issue for me.

**Comment by kelemen** [comment]
No problem but I don't know when exactly will I have a new release. If you need a "correct" build in the mean time checkout the [development](https://github.com/kelemen/netbeans-gradle-project/wiki/Development) page in the wiki. You need to have the JDK 5 and 7 installed. Though, if you only need Java 7 compatibility, you can just add Java 7 to the platforms in NetBeans and now NB should execute the build with Java 7 instead of Java 8.
