### ISSUE TITLE
Opening separate sub-project node can lead to confusion in project group.

### ISSUE THREAD

**Issue by lodici** [kelemen/netbeans-gradle-project#270]
Can an option be added to open sub-projects within the root node tree instead of creating separate project nodes? Here is an example of two [libgdx](https://github.com/libgdx/libgdx/wiki/Project-Setup-Gradle) generated projects in the same project group, the only way to make this work is to have one project open at a time which seems to defeat the point of project groups.
![screenshot00513](https://cloud.githubusercontent.com/assets/2443519/14604175/07ed4c4e-056a-11e6-8924-4a1a0086db37.png)

**Comment by kelemen** [comment]
If projects were accessible through the root project that would effectively mean that you are keeping all projects opened which is inefficient usually.

If your problem is the name of the project, you can configure it to contain the parent name in the global settings.

**Comment by lodici** [comment]
> If your problem is the name of the project, you can configure it to contain the parent name in the global settings.

Thanks, that works.
