### ISSUE TITLE
Project source file encoding not honoured when starting daemon

### ISSUE THREAD

**Issue by mfuerstenau** [kelemen/netbeans-gradle-project#271]
I set the project source file encoding to `UTF-8` resulting in a file `.nb-gradle-properties` with content:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<gradle-project-properties>
  <!--DO NOT EDIT THIS FILE! - Used by the Gradle plugin of NetBeans.-->
  <source-encoding>UTF-8</source-encoding>
</gradle-project-properties>
```
but when I run the `test` task for example I get a gradle daemon with `-Dfile.encoding=windows-1252` (I am using Windows). I made sure no gradle daemon is running before. I use the gradle wrapper (2.12/2.13 bot tested). Option `-J-Dfile.encoding` is NOT SET in `netbeans.conf`. Also `JAVA_OPTS` and `GRADLE_OPTS` environment variables are NOT SET (which are also ignored). No user settings for gradle alter the encoding.

I expect the plugin to honour it's own setting.

**Comment by kelemen** [comment]
The file encoding propery means how the editor of NB should interpret the project's source file.

If you want the Gradle daemon to be started with another file encoding you should set the JVM arguments in the global settings (i.e., set the "file.encoding" system property to the required value)

**Comment by mfuerstenau** [comment]
Yes, of course. but what puzzles we is, that when I set `GRADLE_OPTS` to `-Dfile.encoding=UTF-8` and start gradle from command line, I get a daemon process with `-Dfile.encoding=UTF-8`. But when I use Netbeans I end up with `-Dfile.encoding=windows-1252` despite the environment variable

**Comment by kelemen** [comment]
I don't know but I assume Gradle does not pick up GRADLE_OPTS so that it does not conflict with the tool starting Gradle. Besides, one disadvantage of using environment variables is that you will have to restart the IDE for changes to take effect. So, I recommend you just set the arguments you need (like Xmx and file encoding) in the global settings of NB.

**Comment by mfuerstenau** [comment]
Is there a per project JVM option, because we have projects using ISO-8859-1 and UTF-8? I only see the global JVM option or the task based option.

**Comment by kelemen** [comment]
Sadly, no but it would make sense. Have you tried putting `systemProp.file.encoding=UTF-8` into your root project's *gradle.properties* if it works?

By the way, that property is only relevant for .gradle files. For source files, you should set the appropriate compile task.

**Comment by mfuerstenau** [comment]
> Sadly, no but it would make sense. Have you tried putting systemProp.file.encoding=UTF-8 into your root project's gradle.properties if it works?
Tried it, to no avail. It seems not possible to have different JVM args for different gradle projects, especially with daemon

**Comment by mfuerstenau** [comment]
I found the solution.*Thanks for your effort*. I appreciate your work. To have file encodings per project and I have to create `gradle.properties` in the project with
```
org.gradle.jvmargs='-Dfile.encoding=UTF-8'
```
If the JVM-args differ from existing daemon, a new is created. Also I can check the file into our subversion repository.
