### ISSUE TITLE
Tutorial to Netbeans-Gradle

### ISSUE THREAD

**Issue by bashsha** [kelemen/netbeans-gradle-project#273]
I am new to Gradle (and not familiar with Ant, Maven,...) but an expert in Java coding. Is there any tutorial for building NetBeans Platform CRUD using Gradle similar to these Ant and Maven tutorials?
https://platform.netbeans.org/tutorials/nbm-crud.html
https://platform.netbeans.org/tutorials/nbm-maven-crud.html
Thanks

**Comment by kelemen** [comment]
As far as Java code goes, it is the same. So, I would just start out from the Maven tutorial and then convert it to a Gradle project (preferably using [Radim's NBM plugin](https://github.com/radimk/gradle-nbm-plugin).
