### ISSUE TITLE
Multiple Source Sets - Issue Following Sources

### ISSUE THREAD

**Issue by qcsoftware513** [kelemen/netbeans-gradle-project#274]
It seems Netbeans does not properly resolve the source paths (as far as jumping using ctrl+shift+B) in certain circumstances. i have two source sets as follows:
/Src
/QcUpdates
I also have a library jar file with source code as follows:
someLibrary-12.1.0.jar
I create a newer version of the class file that exists in the library in QcUpdates source. Then i reference that new code from the Src directory. Everything compiles ok and there are no red x's, but if i try to jump to the code, it always reverts to the jar file.

is there a way to identify if sources are set up in the wrong order?

I have attached a sample project.
[Sample.zip](https://github.com/kelemen/netbeans-gradle-project/files/247723/Sample.zip)

**Comment by MT-AKelemen** [comment]
As far as a the plugin can see, your source set depends on a .jar file. Why do you think the plugin should decide that that (seemingly unrelated) .jar file is created from your other source set?

Also, if I can advise something: Use the standard java plugin of Gradle and don't create your own compile task (you can configure Gradle's compile tasks as well). That is I recommend you creating a standard build which you configure. As is now, you are fooling the plugin (and most likely any other tool) completely by adding the jar file which contains your compiled sources. You should never do that, if two source set depends on each other, then you should only add the sourceset's output as a dependency for that source set.

**Comment by kelemen** [comment]
As far as a the plugin can see, your source set depends on a .jar file. Why do you think the plugin should decide that that (seemingly unrelated) .jar file is created from your other source set?

Also, if I can advise something: Use the standard java plugin of Gradle and don't create your own compile task (you can configure Gradle's compile tasks as well). That is I recommend you creating a standard build which you configure. As is now, you are fooling the plugin (and most likely any other tool) completely by adding the jar file which contains your compiled sources. You should never do that, if two source set depends on each other, then you should only add the sourceset's output as a dependency for that source set.

**Comment by JustGregory** [comment]
One point I would like to add, *I feel* at least, it may be best to _not_ use anything other than all lower-case directory names for the source-sets. Why? I don't know. Other than that gradle projects already (only) use lower-case pathnames; it just makes a certain amount of sense to keep with the original style of something. Is using `Src` and `QcUpdates` really so important as to contain mixed-case?

**Comment by qcsoftware513** [comment]
No need for the mixed case.  Mostly just bad conventions…

I think I made it work by using a single source set with multiple sources, however.

Mike
