### ISSUE TITLE
Some gradle tasks not showing up in project->tasks

### ISSUE THREAD

**Issue by fwelland** [kelemen/netbeans-gradle-project#275]
This is an odd one and would understand if prioritized in a low fashion or not at all since there is a sort of  work-a-round.     

 Here are the details: 

*  multi-project build
*  In the root build.gradle IN the subprojects block there is this bit of code: 

`    if(file('local.gradle').exists()){
        apply from: 'local.gradle'
    }`

* the affect of this is: if in a project sub-dir having a build.gradle (as listed in setting.gradle) there is a local.gradle file; then include/apply the contents of that gradle along with the sub-dir's build.gradle

* in my 'web' sub-dir, my local.gradle applies a plugin and then also declares 3 tasks. 

* netbeans 8.1, G4NB 1.3.8.1, JDK 1.8.0_77, gradle (via wrapper) 2.12, linux/fedora23

**The problem**

The tasks added by the plugin show up just fine in the projects->tasks list.   The tasks that are simply defined in the local.gradle  do NOT show up in projects->tasks. 

However, I can totally do project->Custom Tasks  and make a new  custom task entry and type in the name of the task omitted from projects->Tasks and save and execute that.  That custom task works doing the correct thing (invokes the 'invisible task').   The project->Tasks inventory isn't' affected by this and still will not display those tasks from the applied local.gradle. 

Is there some way to make these applied tasks display in project->tasks? 

(Is this problem description clear?)

**Comment by kelemen** [comment]
Can you try if this helps:

	def localGradle = file('local.gradle')
	if (localGradle.exists()) {
		apply from: localGradle
	}

Also, it would be nice if you could share a project with which I can reproduce the issue with because I believe it should work.

**Comment by fwelland** [comment]
tried that  (def localGradle...);    didn't really change anything.   

I think I have a github project kicking around that does this same thing....I will look for it and it and post back...Or (try to) create a quick hackup showing the behavior.

**Comment by fwelland** [comment]
Reproduced this in a hack.     Here is the repo:    https://github.com/fwelland/Flop

**Comment by kelemen** [comment]
I could reproduce the your issue and it seems to be a strange bug in Gradle.

That is, I'm retrieving the tasks with the following code:

    private Collection<GradleTaskID> findTasks(Project project) {
        TaskContainer tasks = project.getTasks();

        // Note: This might cause failures in Gradle 2.4-rc-1
        // due to GRADLE-3293. (in practice however, we do not request
        // custom models and GradleProject together).
        List<GradleTaskID> result = new ArrayList<GradleTaskID>(tasks.size());
        for (String taskName: tasks.getNames()) {
            Task task = tasks.findByName(taskName);
            if (task != null) {
                String name = task.getName();
                String fullName = task.getPath();
                result.add(new GradleTaskID(name, fullName));
            }
        }

        return result;
    }

and this code actually won't retrieve tasks created in the applied script file. However, I have tried and if I create tasks the very sameway directly in your *build.gradle*, it will list the tasks.

I think you should report this issue to Gradleware.

**Comment by kelemen** [comment]
I have tested it and it got broken between Gradle 2.3 and 2.4.

**Comment by fwelland** [comment]
wow...ok thanks for checking this out.   

To thicken the soup a bit, when I was creating this sample, I had a single gradle project that was essentially 'rdr'  as you see it now -- with the local.gradle apply stuff.    I was hoping the problem didn't involve a multi-project setup - it does.      Works just fine in a single root project with the local.gradle stuff.   

I had to move rdr to a sub and add the root project for the problem to come back.      I'll check with the gradlware folks about it. 

Again, thanks for checking this out and thanks for all the work you do with G4NB!!!!
