### ISSUE TITLE
unit test multiproject 

### ISSUE THREAD

**Issue by salahaldin** [kelemen/netbeans-gradle-project#280]
I have multi project gradle , but each subproject can build in a stand alone manner. I can build the project but I can not test or debug test files. 

when I run test I get 
* What went wrong:
Execution failed for task ':test'.
> Could not find matching test for pattern: com/xxx/yyy/zzTest 
I can run unit test from command line like this 
/cygdrive/c/dev/local_tools/gradle-2.14/bin/gradle cleanTest   -Dtest.single=com/xx/yyy/zzTest
Net beans generate the following command
Executing: gradle :cleanTest :test
Arguments: [-Dtest.single=com/xx/yyy/ccTest, -c, C:\dev\MyApps\xxx\yyy\settings.gradle]

I tried to remove the settings.gradle in the sub-project but still gets the same error

**Comment by kelemen** [comment]
If you are using Gradle 2.13 (or above) and have a *buildSrc* project, then it is most likely issue #272 which is fixed in master. You can refer to the issue on how you can work around it or build the plugin from the sources for now.

**Comment by salahaldin** [comment]
Thank you, for referring to the issue
