### ISSUE TITLE
Gradle plugin in Netbeans 8.1 with JavaFX

### ISSUE THREAD

**Issue by njss** [kelemen/netbeans-gradle-project#282]
I could not use this gradle project:
https://github.com/EyeTribe/tet-java-client

**Comment by kelemen** [comment]
Works fine for me. What are you trying to do and what happens?

**Comment by JustGregory** [comment]
@njss 
I hope you know that javafx plugin is no longer being maintained; more recently it's been forked into the @FibreFoX/javafx-gradle-plugin repository; please also check there, for more "modern" JavaFX + Gradle support....

**Comment by FibreFoX** [comment]
Just for the record: I haven't forked it, my [javafx-gradle-plugin](https://github.com/FibreFoX/javafx-gradle-plugin) was built upon the [javafx-maven-plugin](https://github.com/javafx-maven-plugin/javafx-maven-plugin), which was created by @zonski, not the project @shemnon did on bintray :smile_cat:

**Comment by njss** [comment]
I've changed the path of Gradle in Netbeans to a local new Gradle installation. After this I could load and compile the project.

I get the following messages while compiling the SDK:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sdk:test'.
> When running gradle with java 8, you must set the path to the old jdk, either with property retrolambda.oldJdk or environment variable JAVA5_HOME/JAVA6_HOME/JAVA7_HOME
------------------
While compiling the example, I get this error on Gradle:

* What went wrong:
Could not read path 'D:\...'
-----------------------------------

Maybe the path is too long?

Anyway, Because I do not have much time to spend, I've decided to create a new Maven project in Netbeans and import all dependencies manually, finally, I could compile it and run it.
But it is a bit cumbersome of course.
That is why we like Maven and Gradle...

Thanks for the help.
Nelson

**Comment by kelemen** [comment]
I can load and build the project without any problem (even without specifying a local Gradle distribution). Maybe you are behind a proxy and it is not configured properly.

As for running the tests for "sdk", I suggest you follow the setup steps described in the project's readme.

**Comment by JustGregory** [comment]
Ah, sorry for forgetting where it came from, @FibreFoX .

(I've been using Gradle for a year or so, but in many ways I'm still "new" to JavaFX in Gradle. It was my goof in misunderstanding and mis-stating where it came from.)
