### ISSUE TITLE
[Improvement] Make gradle build task clear the output window before sending output.

### ISSUE THREAD

**Issue by MarceloRuiz** [kelemen/netbeans-gradle-project#284]
I think it could be great if the execution of the task could trigger a clear action on output window, so the information presented there reflects only the last build.
Right now I need to trigger the clear action manually or I need to scroll manually to see the output of the most recent build.
Thanks!

**Comment by kelemen** [comment]
There is already a global option to set this behaviour. See the [wiki](https://github.com/kelemen/netbeans-gradle-project/wiki/Task-Execution).

**Comment by MarceloRuiz** [comment]
Thanks, my bad. I totally overlooked that option.

**Comment by MarceloRuiz** [comment]
I don't want to start another issue for this question: I noticed that while debugging NetBeans does not show the variables information and it says the code should be compiled with the "-g" option. Could you please tell me how to solve this?
Thanks!

**Comment by kelemen** [comment]
It means that the code you are looking at have the debugging info stripped. If it is an external library, you might try to ask the owner of the library or compile that library without stripping the  debug info. See the [documentation of javac](http://docs.oracle.com/javase/7/docs/technotes/tools/windows/javac.html) about hte *-g* option.

**Comment by MarceloRuiz** [comment]
Thank you!
