### ISSUE TITLE
Netbeans shows error in editor, but project compiles and runs fine in command line

### ISSUE THREAD

**Issue by MarceloRuiz** [kelemen/netbeans-gradle-project#285]
I am having trouble with this project: [https://dl.dropboxusercontent.com/u/7707848/project.zip](url), which is part of a Griffon tutorial.
When I open it with NetBeans, the editor shows an error stating it cannot find a method that belongs to an interface. The funny thing is that if I navigate to the code the method does not exist, but the project compiles, runs and tests with no errors using gradle from the command line or using gradlew.
Any idea of why this is happening?

**Comment by kelemen** [comment]
Running `gradlew compileFunctionalTestJava` fails with a compilation error for me, so I think NetBeans' editor is right to tell you that didn't exit.

**Comment by MarceloRuiz** [comment]
@kelemen 
You're right, closing this one now.
I guess it is a different issue then, maybe related to project caching in NetBeans: sometimes when I close a project and make changes in an external editor and open it again in NetBeans it does not reflect the new changes...

**Comment by kelemen** [comment]
If NetBeans fails to refresh after external changes, try *Source/Scan for External Changes*, it might help.
