### ISSUE TITLE
[Improvement] Show name of root project in open subproject menu or rearrange hierarchy

### ISSUE THREAD

**Issue by MarceloRuiz** [kelemen/netbeans-gradle-project#286]
When working with 2 different projects that have a same subproject name it gets really confusing because there is no way to detect which subproject belongs to which root project. 
I see two ways of solving this: 

- Prevent subprojects to open as a main project (at first level of projects tree) and instead open them within the root project, which will give a clear and accurate representation of the project's real structure. 

- Add the root project name to the subproject node representation. It could be something like [subproject]::[root project] where ::[root project] could have a font that is not as bright at the one used for [subproject].

See attached picture for example of how confusing the current representation is.

![selection_031](https://cloud.githubusercontent.com/assets/1209270/17821006/6f795f56-661d-11e6-8041-d7ce327c2af7.png)

**Comment by kelemen** [comment]
You can select different naming in the global settings of Gradle project.

Displaying projects directly under the subprojects node is good theoretically but that would imply that all projects will be loaded into memory which is something I wish to avoid. Also, deep structure is often inconvenient to work with.

**Comment by MarceloRuiz** [comment]
Could you please tell me how I can show the root project name? 
I tried in Tool->Options->Miscellaneous->Gradle->Appearance: Project node name: Custom
And then I tried:  ${project.name} - ${rootProject.name}
but I cannot make it work (project node is resolved, but not the root project name).
Thanks!

**Comment by kelemen** [comment]
You can only use variables which are listed in the predefined ones. So, you will probably want ${project.path} for a fully qualified project name.

**Comment by MarceloRuiz** [comment]
Thanks for the answer.
Is there any way to define another variable? ${project.path} is overkilling for this...

**Comment by kelemen** [comment]
Not without modifing the code. It is not a big deal to add variables however. `DisplayableTaskVariable` has to be adjusted for this appropriately.

**Comment by MarceloRuiz** [comment]
Just in case, I modified the class and it's working now. In case you need the code for a future version, here it is: [https://dl.dropboxusercontent.com/u/7707848/DisplayableTaskVariable.java](url)
Thanks for your help!

**Comment by kelemen** [comment]
By the way, I have just added some improvement to displaying the project name (now there are variables like `${parent.name}` as well). Also, it is now possible to configure the project display per multi project build (not only in the global settings).

**Comment by JustGregory** [comment]
Please do not forget that aside from the Projects panel, there is also a Files panel, which will show hierarchically the files and folders beneath any opened project ... So, organizationally it may not be so important to see from the Projects panel....

**Comment by MarceloRuiz** [comment]
@JustGregory 
I don't know if I understand what you said correctly, but my point to have the naming in the project view is that usually packages are shown in a single line, which helps with the limited vertical real state compared to the Files view.

**Comment by MarceloRuiz** [comment]
@kelemen 
Hi Attila, that is great! I think it would help a lot. Is it available for general public?
I don't know if you could access the code through the link I posted: for some reason I can't from the post, so I will paste here the relevant lines of code in case you want to reuse them:

`
```
    PROJECT_CHILD_PARENT("project.child.parent",
            new ValueGetter<NbGradleModel>() {
        @Override
        public VariableValue getValue(TaskVariableMap variables,
                NbGradleModel model, Lookup actionContext) {
            return new VariableValue(getSafeChildParentProjectName(model));
        }
    }),
    PROJECT_PARENT("project.parent",
            new ValueGetter<NbGradleModel>() {
        @Override
        public VariableValue getValue(TaskVariableMap variables,
                NbGradleModel model, Lookup actionContext) {
            return new VariableValue(getSafeParentProjectName(model));
        }
    }),

*********************************************


    private static String getSafeParentProjectName(NbGradleModel model) {
        if (model.isRootProject()) {
            return model.getProjectDef().getRootProject().getProjectName();
        } else {
            return "";
        }
    }

    private static String getSafeChildParentProjectName(NbGradleModel model) {
        StringBuilder compoundName = new StringBuilder(100);

        compoundName.append(getSafeProjectName(model));

        if (!model.isRootProject()) {
            compoundName.append("  ::  ");
            compoundName.append(model.getProjectDef().getRootProject().
                    getProjectName());
        }
        return compoundName.toString();
    }
```

`

Thanks!

**Comment by kelemen** [comment]
@MarceloRuiz Not yet but you can build the project (it should build out-of-the-box) for yourself. The changes are already in master. Other: JustGregory reflected on your first solution on organizing the whole project under the root project.

**Comment by MarceloRuiz** [comment]
Thanks to both of you!

**Comment by MarceloRuiz** [comment]
@kelemen 
Regarding the point of "project.child.parent", the custom format does not allow you to achieve what I did through code. That is especially true when you add extra characters (like my " :: ") and their appearance is linked to the existence of a parent project (which is not the case for the root project). So, in case the evaluated project is the root project, the behavior you defined is used: `projectName [root]`, instead of an awkward `projectName ::`

I want to enhance the way it is displayed even further. I tried to define the strings with built in html tags but they do not get evaluated (as they would do in swing). Could you please point me to the right part of the code where I could change that behavior? 

Thanks again!

**Comment by kelemen** [comment]
`${project.name}::${parent.name}` would yield "projectName:: [root]" which is slightly awkward but I don't think it really warrants such a special case (I would rather use something more generic solution).

In `GradleProjectLogicalViewProvider.GradleProjectNode`, you would also need to override the `getHtmlDisplayName`, though care should be taken so that it does not break when the name is not using html tags.
