### ISSUE TITLE
Do not truncate stack trace lines in test results

### ISSUE THREAD

**Issue by fortiernor** [kelemen/netbeans-gradle-project#297]
When a test fails the Test results window shows a stack trace but lines are often truncated, ending with eg: "... (34 chars omitted)". The tooltip for the line is truncated as well.

This forces user to go to the Output window, click on the link to open the test result in the browser, switch to the browser window, click on the link to the test result, to obtain the rest of the line (typically a method name and a line number).

Enhancement: display stack trace in test results without truncating lines, or at least provide full line as a tooltip.

Thank you for your work!

Possibly related to #291.

**Comment by kelemen** [comment]
This truncating is not done by this plugin but NetBeans itself, so I can't fix this issue. You might report it against the gsf test runner api of NB.

**Comment by fortiernor** [comment]
Thanks for the pointer, will do.
