### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by svatos-jirka** [kelemen/netbeans-gradle-project#299]
Hi,

I am very glad to see gradle plugin for netbeans.
I am using NB 8.1 and Gradle plugin 1.3.8.1, I am not able to load project from https://github.com/kelemen/netbeans-gradle-project.git; it is still resolving and resolving and nothing is resolved :-( may be it could be some proxy or other, but in Netbeans proxy is set up correctly, in general gradle settings too (maven also). So, could you give me some advice, how to find, where the root cause is.

Thanks, Jiri

**Comment by kelemen** [comment]
There are some known issues when using proxies. Please read about it (and about workarounds) in issue #139. If you can solve your problem based on that, please report how you did, so that I might add something to help with proxies.

**Comment by svatos-jirka** [comment]
One  workaround is - just use nexus or artifactory or archiva ....
