### ISSUE TITLE
Single tests fail after 1.3.9.1 upgrade

### ISSUE THREAD

**Issue by avksoft** [kelemen/netbeans-gradle-project#301]
After updating to version 1.3.9.1 of the Gradle plugin, I cannot run "Test File" (Ctrl+F6) to test a single file. It fails with 
`No tests found for given includes: [com.purch.bi.marketing.facebook.AJDailySpendLoader]`
This works on two other machines with 1.3.9 with the code from the same git repository.
I noticed that command that is being executed has changed:
On 1.3.9 it runs:
```
Executing: gradle :FacebookMarketing:cleanTest :FacebookMarketing:test
Arguments: [-D:FacebookMarketing:test.single=com/purch/bi/marketing/facebook/AJDailySpendLoader, -c, C:\Users\avk\Documents\NetBeansProjects\Lambda\settings.gradle]
```
On 1.3.9.1 it runs (and fails)
```
Executing: gradle :FacebookMarketing:cleanTest :FacebookMarketing:test --tests com.purch.bi.marketing.facebook.AJDailySpendLoader
Arguments: [-c, C:\Users\avk\Documents\NetBeansProjects\Lambda\settings.gradle]
```

I get the same error if I execute that command manually from cmd (my project is using Gradle Wrapper 3.1):
```
C:\Users\avk\Documents\NetBeansProjects\Lambda>gradlew :FacebookMarketing:cleanTest :FacebookMarketing:test --tests com.purch.bi.marketing.facebook.AJDailySpendLoader -c C:\Users\avk\Documents\NetBeansProjects\Lambda\settings.gradle
Incremental java compilation is an incubating feature.
:FacebookMarketing:cleanTest
:Shared:compileJava UP-TO-DATE
:Shared:processResources UP-TO-DATE
:Shared:classes UP-TO-DATE
:Shared:jar UP-TO-DATE
:FacebookMarketing:compileJava UP-TO-DATE
:FacebookMarketing:processResources UP-TO-DATE
:FacebookMarketing:classes UP-TO-DATE
:SharedTest:compileJava UP-TO-DATE
:SharedTest:processResources UP-TO-DATE
:SharedTest:classes UP-TO-DATE
:SharedTest:jar UP-TO-DATE
:FacebookMarketing:compileTestJava UP-TO-DATE
:FacebookMarketing:processTestResources UP-TO-DATE
:FacebookMarketing:testClasses UP-TO-DATE
:FacebookMarketing:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':FacebookMarketing:test'.
> No tests found for given includes: [com.purch.bi.marketing.facebook.AJDailySpendLoader]
```

I did run the test gradle task on the whole project and that worked out fine. I then executed 'Run again' from the test results tab on that one test - which executed successfully. I did notice that command for that single test was slightly different:
From run again:
```
gradle :FacebookMarketing:cleanTest :FacebookMarketing:test --tests com.purch.bi.marketing.facebook.AJDailySpendLoaderTest
Arguments: [-c, C:\Users\avk\Documents\NetBeansProjects\Lambda\settings.gradle]
```
From pressing Ctrl+F6 on the source file for which I want to run the test:
```
gradle :FacebookMarketing:cleanTest :FacebookMarketing:test --tests com.purch.bi.marketing.facebook.AJDailySpendLoader
Arguments: [-c, C:\Users\avk\Documents\NetBeansProjects\Lambda\settings.gradle]
```

The difference being that "run again" calls for AJDailySpendLoaderTest and Ctrl+F6 with new version calls for AJDailySpendLoader (without the Test). So it looks like there may be a bug with how the new version of plugin is generating the test single command. For now the work around is to just run all tests or execute test while in the the test file itself (or focused test method) as opposed from the source file... 

Thanks for the wonderful plugin!
Alex

**Comment by kelemen** [comment]
I have fixed this in master (the issue can be reproduced with Gradle version 2.3 or later). You may build the plugin from the sources or use one of these workarounds:

- Run the tests from the test class itself (and not the class being tested).
- Reconfigure the "Test Single" built-in task: Append a "*" character after (without spaces) `${selected-class}`. That is change it to `${selected-class}*`.
- Use an old (2.2 or older) Gradle version *not recommended*.

**Comment by avksoft** [comment]
Awesome! Thank you!

**Comment by avksoft** [comment]
1.3.9.2 update resolves this! Thanks again!
