### ISSUE TITLE
Can't disable the plugin / turn off builds

### ISSUE THREAD

**Issue by kurtseebauer** [kelemen/netbeans-gradle-project#305]
I'm using Netbeans 8.2 and a project with the traditional ant buildfieles and there are gradle files present. The gradle plugin uses the gradle files to build without asking and I am not able to turn off this behaviour. 
I can't even find the plugin in the plugins list anymore, has it been integrated into mainline Netbeans? 

Please provide a feature or help to turn off the gradle build. 
Thanks!

**Comment by Hillkorn** [comment]
1. It is bundled with the other in "User Installed Plugins" and it should be possible to disable it by activating the "show details" under the installed tab of your plugins overview in netbeans.
2. The plugin usually checks for a build.gradle file to decide that it is a gradle project. You could rename it to avoid netbeans setting it up as a gradle project. (Maybe you need to delete the /nbproject folder)
3. I don't really understand why you have a gradle setup in a project that uses a ant as a setup.

**Comment by kurtseebauer** [comment]
1. yep, thanks, that works
2. renaming isn't a good option, because I works with the the files. Some programmers use IntelliJ, some Netbeans and we are currently migrating away from ant to gradle which also answers ...
3. not yet ready to dispose the ant files.

**Comment by JustGregory** [comment]
kurt, what does migrating away from Ant mean to you? Just a stab in the dark, but, the sooner you can get the whole team on a Gradle build development, the better AND easier it should all be. This Youtube vid https://youtu.be/mvBoIro4go4 is an interesting watch, for starters. That Hans Dockter is quite an interesting guy....

Not sure if you mean the transition requires reading through lines of Ant build files or not, but - it's not like things from the Ant buildscript will be of any use anymore; and it's far more useful to visit the Gradle wiki, forums, and doc pages to know how to do something in gradle-scripts. For my own old projects, I simply create a new Gradle project, drag-n-drop the source files, and dispose of the Ant project files; done and done.

**Comment by Hillkorn** [comment]
In general you can run ant tasks from gradle. Could help for a smooth transition.
Look here https://docs.gradle.org/current/userguide/ant.html

**Comment by kurtseebauer** [comment]
Thanks @JustGregory and @Hillkorn , I think we are on a pretty good path. The project structure has some complexities and we need to unravel some dependency crap, before we are done. :-)
