### ISSUE TITLE
quick opener doesnt work with gradle project

### ISSUE THREAD

**Issue by svatos-jirka** [kelemen/netbeans-gradle-project#312]
Hi,

I used nice plugin https://github.com/dzsessona/QuickOpener-NetBeans. But the plugin doesnt work for gradle project. I think, that it is caused missing instance of DataObject in lookup.

Could you help?

From QuicOpener-NetBeans plugin?

 @Override
    protected boolean enable(Node[] activatedNodes) {
        file = null;
        if (null != activatedNodes && activatedNodes.length == 1) {

            file = PathFinder.getActiveFile(activatedNodes[0].getLookup().lookup(DataObject.class), false);
//file is NULL
        }
        return null != file;
    }

**Comment by kelemen** [comment]
I'll see what that plugin does and will try to make an adjustment for interoperability.

**Comment by kelemen** [comment]
Should be fixed in master. You can try if it works for you by building the project yourself (it should build out-of-the-box).

**Comment by svatos-jirka** [comment]
Thanks!
