### ISSUE TITLE
context sensitive action for subproject

### ISSUE THREAD

**Issue by svatos-jirka** [kelemen/netbeans-gradle-project#316]
Hi,

we use subproject. It is great to see subprojectunder parent project. But, If I click to "build/clean and build" on subprojectthen the parent project is clean/build instead of selected subproject. Could you propagate node of subproject  "project interface"  to Utilities.globalContext(). or add below to subproject node:
                    ActionProvider.COMMAND_BUILD,
                    ActionProvider.COMMAND_CLEAN,
                    ActionProvider.COMMAND_COMPILE_SINGLE

Sorry, I am not sure, what steps are needed.

![image](https://cloud.githubusercontent.com/assets/8783570/22302320/816e206e-e32e-11e6-8ba1-660999db9a5b.png)
"red color" button doesnt care about subproject (blue one). only the parent project is avaible for context aware actions.

with best regards, jiri

**Comment by kelemen** [comment]
It shouldn't be a problem, I'll look at this issue next week.

**Comment by svatos-jirka** [comment]
Thanks

**Comment by kelemen** [comment]
This should be fixed in master (the whole context menu was added). Can you try if it works for you?

**Comment by svatos-jirka** [comment]
yes, give me a day please, I will download it, compile and test

**Comment by svatos-jirka** [comment]
Hi, 

sorry, I am not sure how to build it. I was successful do "gradle build" but I was not able to find some "*.nbm" file, which I should install to NB. thanks for help, Jiri

**Comment by JustGregory** [comment]
On the command line, when doing a ```gradle tasks```, does a task exist to generate an nbm file from the build result?

**Comment by kelemen** [comment]
The "build" task will create an nbm (but the "nbm" task will also do so with the least possible work). The nbm file should be in */netbeans-gradle-plugin/build/nbm* but if you read the [Development](https://github.com/kelemen/netbeans-gradle-project/wiki/Development) page, you will be able to test the plugin without installing it into your NB installation.

**Comment by svatos-jirka** [comment]
Thanks, great.

Issue could be closed, I look forward to next release.
