### ISSUE TITLE
Run / Debug / Test tasks to start application in the front

### ISSUE THREAD

**Issue by ThomasDaheim** [kelemen/netbeans-gradle-project#317]
Hi Attila,

first of all thanks for the great plugin!

Let me try to explain my problem I'm facing in the moment - and maybe there is some easy fix :-)

I'm having a maven and a gradle netbeans project for the same javafx application (historical reasons). Under maven if I execute run / debug tasks the application is coming up in the front, replacing netbeans as active window. In gradle the application is running in the back.

That causes my test cases (built with the testfx framework) to fail under gradle since they assume the application is running in front and try to send keystroke to it.

I already have some "bring to front" in the test case. But somehow it doesn't seem to work when started from the gradle tasks.

Thanks in advance for any pointers,
Thomas

**Comment by kelemen** [comment]
I remember having similar issues with a Swing based project back then. However, if I recall correctly, I had problems with Maven as well (altough, in both cases it was not deterministic). I can't remember what I have called but I know I did call everything what I could (i.e., black magic :) ) and it seemed to help.

However, I don't know what could be the cause of this. The best I can think of as something which might cause this behaviour is the `io.getIo().select();` line in [AsyncGradleTask](https://github.com/kelemen/netbeans-gradle-project/blob/master/netbeans-gradle-plugin/src/main/java/org/netbeans/gradle/project/tasks/AsyncGradleTask.java). It would be great, if you could try if commenting this line helps (the project should build out of the box but the conveniently run it, you should read the [Development page](https://github.com/kelemen/netbeans-gradle-project/wiki/Development).

**Comment by ThomasDaheim** [comment]
Thanks for the quick response! Will try that once I have a free cycle :-)

**Comment by ThomasDaheim** [comment]
When I try to run "netbeans-gradle-project [build]" I get "Cannot execute run because the property "mainClass" is not defined or empty." What is the main class of netbeans-gradle-project?

**Comment by kelemen** [comment]
You are trying to run the "buildSrc" project. Run the "netbeans-gradle-plugin" subproject.

**Comment by ThomasDaheim** [comment]
Aaargh - I have to run netbeans-gradle-plugin? There I get

"Warning - could not install some modules: Gradle Support - No module providing the capability cnb.org.netbeans.modules.groovy.kit could be found. Gradle Support - The module named org.netbeans.modules.groovy.support was needed and not found."

when NetBeans starts up first time. Works after installing the Groovy plugin.

Thats maybe worth adding to the Development page...

**Comment by ThomasDaheim** [comment]
Some more findings: when I start netbeans via "run" the gradle plugin is ´not activated by default.

And, even with '''io.getIo().select();''' commented out my application still starts in the background

**Comment by kelemen** [comment]
Yes, probably I should mention that I assume that the developer have the full install of NB containing Groovy.

Anyway, if so, then I don't think this issue is directly related to this plugin. The only other cause I can think of is that your application will be started by a background daemon process and the OS somehow does not think it is important to move a window to the foreground.

Also, I have found this which might shed some light on your problem: https://bugs.openjdk.java.net/browse/JDK-8124521

**Comment by kelemen** [comment]
By the way, why do you have to assume that the application is in the foreground? Can you not ask FXRobot (or something like that) to send messages to a particular window?

**Comment by ThomasDaheim** [comment]
Well, it was just easy to call "stage.toFront();" and then simply send keys & mouse to the active window :-) Need to look into TestFX to send to a specific window...

**Comment by ThomasDaheim** [comment]
Found it... Besides "toFront()" I also need to call "requestFocus()" to have it work under gradle as wel.
