### ISSUE TITLE
Netbeans doesn't see JAR dependency created by subproject

### ISSUE THREAD

**Issue by joebowbeer** [kelemen/netbeans-gradle-project#321]
On the gradle command line, the project AndroidResourceIds builds and runs, and the test passes. But NetBeans 8.2 w/plugin 1.3.9.2 shows an error in the source editor, saying that the *android* package, imported from a jar created by the androidR sub-project, does not exist.

The red-badge is shown at line 11 in App.java:

import android.R; // package android does not exist

Project: https://bitbucket.org/joebowbeer/androidresourceids

The android package is created by the *androidR* subproject, which is declared as a compile dependency of the root project.

A successful test run:

https://circleci.com/bb/joebowbeer/androidresourceids/2

Can some magic be added to build.gradle that will fix this problem in NetBeans?

**Comment by kelemen** [comment]
You need to install [NBAndroid](http://www.nbandroid.org) to develop Android projects in NB (this plugin only provides core features not specific to Android).

**Comment by kelemen** [comment]
Just noticed that this is not an Android project. The issue is that the output of a jar task is assumed to be a project dependency and is replaced with the project's sources. You should somehow create a proper dependency on a jar file and not hack the jar task this way (the dependency might be created by a Gradle task but then you have to manually run that task for NB to detect the jar).

I don't intend to support this use case because it would be extremely complicated (practically impossible) to tell NB that this jar is partly a project dependency and partly not.

**Comment by kelemen** [comment]
You could do something like this:

```groovy
apply plugin: 'java'

task fakeAndroidJar(type: Zip) {
  from zipTree("C:\\Tools\\Android-NDK\\platforms\\android-25\\android.jar").matching {
    include "android/R*.class"
  }
}

classes.dependsOn fakeAndroidJar
dependencies {
    compile files(fakeAndroidJar.archivePath)
}
```

Notice that this uses a `Zip` task instead of a `Jar`. As is now all `Jar` tasks are considered some kind of project dependency (I will try make a workaround, to let users tell NB that this is not the case for a particular jar task).

**Comment by kelemen** [comment]
I have just realized that there is already a way to specify this for a jar task. You should use this code instead:

```groovy
apply plugin: 'java'

task fakeAndroidJar(type: Jar) {
  from zipTree("${System.env.ANDROID_HOME}/platforms/android-25/android.jar").matching {
    include "android/R*.class"
  }
  // Have to rename not to produce the same jar as the 'jar' task.
  baseName = 'fakeAndroidJar'

  // Tells NB that there are no sources associated with this task.
  ext.netBeansSourceSets = []
}

classes.dependsOn fakeAndroidJar
dependencies {
    compile files(fakeAndroidJar.archivePath)
}
```

**Comment by joebowbeer** [comment]
Great. Thanks!

I was able to remove the androidR subproject and combine everything into one simple build file:

```gradle
apply plugin: 'java'

task fakeAndroidJar(type: Jar) {
  from zipTree("${System.env.ANDROID_HOME}/platforms/android-25/android.jar").matching {
    include "android/R*.class"
  }

  // Have to rename not to produce the same jar as the 'jar' task.
  baseName = 'fakeAndroidJar'
}

compileJava.dependsOn fakeAndroidJar

dependencies {
  compile files(fakeAndroidJar.archivePath)
  testCompile group: 'junit', name: 'junit', version: '4.10'
}
```
