### ISSUE TITLE
Refactoring, find usages, ... doesnt work

### ISSUE THREAD

**Issue by svatos-jirka** [kelemen/netbeans-gradle-project#324]
Hi,
please, could you improve "classpath of projectA, if the projectA has dependency to projectB and projectB is open". ProjectA has dependency "compile group:artifact:1-SNAPSHOT" to ProjectB (version: 1-SNAPSHOT). I think, that works correctly, if ProjectA has dependency "compile (":projectB"). I think, that classpath of projectA should be redirected to ProjectB, if ProjectB is opened in IDE in right version. In other case classpath of ProjectA should stay to artifact of ProjectB, if ProjectB is not opened in IDE. This is behaviour works in maven project under NetBeans.

![image](https://cloud.githubusercontent.com/assets/8783570/23299369/a94ba344-fa81-11e6-9eb4-ab8ea5a0f613.png)

I like help with this issue, please give some hint :-)

with best regards, jiri

**Comment by kelemen** [comment]
There is a "detect project dependencies by jar name" (in Misc/Gradle/others) which may work if you don't change the version.

Aside from that the current version in master (not the current release) provides support for composite build, so you can organize your build around that. See my comments in #277.

**Comment by svatos-jirka** [comment]
Thank a lot, it works wonderfull!

tested in version  1.3.9.2

with best regards, jiri
