### ISSUE TITLE
Java EE  support

### ISSUE THREAD

**Issue by jGauravGupta** [kelemen/netbeans-gradle-project#334]
Hi @kelemen ,

Please provide the support for JavaEE project. So developer can connect the project with available server in the NetBeans IDE and directly deploy to it.

If support for some features is already available then please share the doc.

**Comment by kelemen** [comment]
EE support is not in the context of this plugin. The [Gradle JavaEE](https://github.com/hildo/netbeans-gradle-javaee-project) plugin should provide any related feature. If you need something, report it there.
