### ISSUE TITLE
Unable to run test

### ISSUE THREAD

**Issue by sander-adhese** [kelemen/netbeans-gradle-project#360]
JUnit tests are present, but I can't run them except through gradle build + run (CTRL-F6), which is really inconvenient. (for starters it takes a long time)
Run Test / Run Test Method should just run it as unit test.
I miss the simple Eclipse's 'run as' menu option.
Any idea's?

**Comment by kelemen** [comment]
Those commands should work (I use them daily), what are you doing exactly?

**Comment by sander-adhese** [comment]
So I've imported my project as gradle project, but the project structure is not Netbeans default. Ergo it can't find out where the test classes live I guess, making the jUnit submenu structure unavailable

**Comment by kelemen** [comment]
Can you share your build, the project structure not being default shouldn't necessarily be a problem.
