### ISSUE TITLE
Subproject A is dependant on subproject B, but cannot find the build classes of B (SOLVED)

### ISSUE THREAD

**Issue by chjan** [kelemen/netbeans-gradle-project#362]
The rootproject contains 3 subprojects, placed side by side as folders in the Windows folder of the rootproject.

B clean&build = OK. The classes from B may also be imported into A, however sometimes after manual reload of project B.

The problem arise when compiling A, as the compiler claims the classes of B do not exist (despite import ok).

Have tried all sorts of NB restart, cache delete, etc, but in vain. I have tried to look into all files without finding any clues for this malfunction. It is probably a blunder on my part, but what?

What could be the possible causes of A not recognising B during compiletime?

Note: I am moving to Gradle for NB due to long time use of Gradle in Android Studio.

**Comment by kelemen** [comment]
I would guess that you put settings.gradle files into the folders of your subprojects but I can't tell without seeing your project (I don't need the actual Java source files).

**Comment by chjan** [comment]
[RxDNSSD_java for Kelemen.zip](https://github.com/kelemen/netbeans-gradle-project/files/1399224/RxDNSSD_java.for.Kelemen.zip)

No big secret since I am porting an existing Android project here on GitHub to pure Java, but sources removed anyway. 

Hope you can spot something. (could be some of the files are Android remnants)

**Comment by kelemen** [comment]
Thanks, I'll be able to have a look at it on monday evening.

**Comment by chjan** [comment]
Note: I created again the rootproject and subprojects. Then I moved the source from the non-working version over to the new, and I added the dependencies that one subproject has to the other.

 

Now it worked, so I did something wrong the last time. Perhaps a good idea to find what is missing, to help others, but my problem was solved.

 

I see in the new version one difference; the “dependency” folders. So I guess this would be the place to look. 

 

Kind regards / Vennlig hilsen

 

Carl Henrik Janson

+47 951 048 00

**Comment by kelemen** [comment]
I'm not exactly sure what happened for you because putting dlls into the jar should break compilation.

As for the native dependency: It is not a Gradle issue, you just have to make Java be able to locate your dlls (e.g.: by setting the PATH variable). However, you will need to manually create a *run* task and set it up properly to be able to run your application.

**Comment by chjan** [comment]
It did break the compilation, confirmative. IOW it was the wrong approach.

FYI, I am able now to load dlls. I could not the netbeans gradle plugin to do that, because it is abandoned. I simply put the dlls in the classpath.

Your plugin is working fine. Thanks for your efforts. I prefer gradle and will use this library in forthcoming projects.

**Comment by kelemen** [comment]
The current plan is to add this plugin to be part of the official NB package. Some problem needs to be solved to do that but it should be part soonish.

**Comment by chjan** [comment]
Excellent! One idea: What if you took a quick look at the Gradle native plugin here on GitHub? Perhaps it is a small job for you to make it work? Why? Because the use of JNI native layers are "commodity" in the pure Java world, and because Gradle does not provide that feature in their own Java plugin. I suppose the reason is that Gradle so far has been focusing on Android. In the Gradle Android plugin, this feature is working well. For your consideration.

**Comment by kelemen** [comment]
Which plugin exactly? (this: https://github.com/cjstehno/gradle-natives?) Also, what do you mean by "make it work"? What support do you expect exactly? If you want some features to be added to this plugin, so that it recognizes something, can you open another issue?

**Comment by chjan** [comment]
I mean that project, yes, i.e. that you could enhance your own plugin by including this native add-on, since "native" is lacking in the normal Gradle Java plugin. 

That gradle-natives plugin was recently abandoned by the developer. It doesn't work properly at the moment, but my guess is that there is not much work to do. I have no idea whether it will be possible, so it was just a loose suggestion on the fly.

**Comment by kelemen** [comment]
Can you open a new issue explaining what is happening now and what exactly do you expect to happen? Because I have no intention to analyze that plugin as I do not currently have any project with native dependencies (I used to years ago but I have manually coded the support in our build).

**Comment by chjan** [comment]
I am sorry, no time to involve further. It was just a loose suggestion to possibly enhance your own project. Not a need I have at the moment.
