### ISSUE TITLE
Upgrade Tooling API Version to 3.0+

### ISSUE THREAD

**Issue by GregAlbiston** [kelemen/netbeans-gradle-project#373]
When building a Gradle project the warning "Support for clients using a tooling API version older than 3.0 was deprecated and will be removed in Gradle 5.0. You are currently using tooling API version 2.13. You should upgrade your tooling API client to version 3.0 or later." is issued.

Warning occurs with Netbeans 8.2, Gradle 4.3 and NB Gradle Support plugin latest version.

Can the plugin be updated to the latest API client before it is removed from Gradle?

**Comment by kelemen** [comment]
It is updated on the nb9 branch but I didn't update it in the previous version because then my plugin would not be backward compatible. It might not be the case for Gradle 4.3 though. If so, I will update it for 8.1/8.2 as well before it becomes an issue.

**Comment by GregAlbiston** [comment]
Ok, that's good to know. 
Thanks for the prompt response and the tool.
