### ISSUE TITLE
NetBeans no longer has the latest release

### ISSUE THREAD

**Issue by TheMorganHub** [kelemen/netbeans-gradle-project#375]
It says in your readme that I can get the latest release from `http://plugins.netbeans.org/plugin/44510/gradle-support` but sadly that's no longer the case. The version provided by NetBeans comes with Gradle 2.13. How can I get the nbm file of the current release on GitHub?

**Comment by kelemen** [comment]
Sorry, I will build a new release this week. Until then, you can download the nbm from https://github.com/kelemen/netbeans-gradle-project/releases/download/v2.0.0.1/netbeans-gradle-plugin-2.0.0.1.nbm

**Comment by TheMorganHub** [comment]
What version of NetBeans are you using? I'm on 8.2 and when I try to install the plugin you just linked it's not letting me and it's showing me this message telling me some of the components I have are outdated. I tried to look for updates to my current plugins but it says everything on my NetBeans is up to date. Therefore I can't run the updated version of your plugin.
![6fw48gj](https://user-images.githubusercontent.com/26914813/37503207-c84af0ac-28b5-11e8-94ba-165dab39d3e5.png)

**Comment by fwelland** [comment]
Ran into the same problem.   Maybe this nbm was built against apache NB and won't work for the older netbeans.org version? 

Longtime G4NB user.  It has worked wonderfully over the last couple years.   I really appreciate the effort you put in to this. 

My Netbeans details
Product Version: NetBeans IDE 8.2 (Build 201609300101)
Updates: NetBeans IDE is updated to version NetBeans 8.2 Patch 2
Java: 1.8.0_162; Java HotSpot(TM) 64-Bit Server VM 25.162-b12
Runtime: Java(TM) SE Runtime Environment 1.8.0_162-b12
System: Linux version 4.15.7-200.fc26.x86_64 running on amd64; UTF-8; en_US (nb)

**Comment by kelemen** [comment]
The linked release is for NB 9, for 8.1 and 8.2, the current latest is https://github.com/kelemen/netbeans-gradle-project/releases/download/v1.4.2/netbeans-gradle-plugin-1.4.2.nbm

**Comment by Soheibooo** [comment]
Yeah a new release would save a **lot** of hassle. Same with the issue right here: #364 Thanks for your effort! This plugin is great _nevertheless_.

**Comment by TheMorganHub** [comment]
So development from now on will be for Apache NetBeans exclusively?

**Comment by kelemen** [comment]
I will add important fixes and possibly smaller improvements to previous versions but not for too long. Though, I will see, it depends on the need.

**Comment by TheMorganHub** [comment]
Alright, I will be closing this issue now. Thank you for the great work you do and for taking the time to respond to this issue!
