### ISSUE TITLE
CompileOnly Dependencies

### ISSUE THREAD

**Issue by andreaseberhoefer** [kelemen/netbeans-gradle-project#378]
In Version 2.0.0.2 compileOnly dependencies don't work. If I declare a compileOnly dependency  (immutables.org) it is shown in the dependency-tree (under "Provided for main"), but I can't use it in my code. In older versions of this plugin, it works as expected.

**Comment by andreaseberhoefer** [comment]
After restart of netbeans it works... sorry

**Comment by kelemen** [comment]
No problem, though it is still strange that restart helped.
