### ISSUE TITLE
Gradle 5 - leftShift(Closure) method deprecated 

### ISSUE THREAD

**Issue by aplatypus** [kelemen/netbeans-gradle-project#379]
The first line of our gradle build files prints the file's name to the Gradle output (see below)  Gradle 4.6 is reporting an error on the `leftShift { }` closures _before_ our first line. 

We've looked at the stack trace and it must be coming from the gradle plugin or some contained script some place.  Before our build file even gets read.

You need to set:

-  `--warning-mode=all`

To see the message.

```

The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.

[tmacs/foundation/build.gradle]
```

**Comment by kelemen** [comment]
I don't use the "<<" operator (I never liked it the first place). I have also checked the sources of the plugin it never uses it (searched for "<<" and the only match was a bit shift in the code). So, I would guess that it might be in one of the plugins you are using.

**Comment by aplatypus** [comment]
Thanks, yes I agree the `<<` isn't a good look.  It ought to be possible to identify the plugin.

**Comment by aplatypus** [comment]
I found the cause of this message this week.  It was coming from the release plugin.  I had v2.4.  v2.7 resolves that error.
```
plugins
{
    id 'net.researchgate.release' version '2.7.0'
    id "base"                           //    To add "clean" task
      :
}
```
