### ISSUE TITLE
Current directory when running Gradle script is not project directy, but root directory of disk

### ISSUE THREAD

**Issue by ksilz** [kelemen/netbeans-gradle-project#380]
Hello,

I've customized my Gradle build for a "Spring Boot Fat JAR" project so that it updates a build file and creates a ZIP file at the end. This doesn't work when running the Gradle tasks in Netbeans because the "Java current directory" is the root directory of my hard disk:

![running in netbeans](https://user-images.githubusercontent.com/1061209/38079939-71983086-3340-11e8-9967-3cc49bcc4bb4.png)

When running the same Gradle script from the terminal, the "Java current directory" is the project directory, as it should be:

![running in terminal](https://user-images.githubusercontent.com/1061209/38079952-7a75b278-3340-11e8-931b-393dc2b6fff8.png)

This is the test project used above:

[TestDirectory.zip](https://github.com/kelemen/netbeans-gradle-project/files/1859302/TestDirectory.zip)

Below's my environment data. I'm using version 1.4.3 of the Gradle plugin: 

Product Version: NetBeans IDE 8.2 (Build 201609300101)
Updates: NetBeans IDE is updated to version NetBeans 8.2 Patch 2
Java: 1.8.0_162; Java HotSpot(TM) 64-Bit Server VM 25.162-b12
Runtime: Java(TM) SE Runtime Environment 1.8.0_162-b12
System: Mac OS X version 10.13.3 running on x86_64; UTF-8; de_DE (nb)
User directory: /Users/Karsten/Library/Application Support/NetBeans/8.2
Cache directory: /Users/Karsten/Library/Caches/NetBeans/8.2

Is there a setting I need to change to have the Gradle build script run in the project directory? Or is this a bug?

**Comment by ksilz** [comment]
Thank you for the hint! I now use the build directory to get the working directory and then access files relative to this working directory:

```
final String workingDir = project.buildDir.toString() + "/../"
File propsFile = new File(workingDir + 'src/main/resources/build-version.properties')
```

**Comment by kelemen** [comment]
It is much better to write this instead:

```groovy
// Project.file resolves relative paths against the project directory
File propsFile = file('src/main/resources/build-version.properties')
```
or a more robust code would be:

```groovy
File propsFile = new File(souceSets.main.resources.srcDirs[0], 'build-version.properties')
```

The above code snipets yield the same result as you code.

**Comment by ksilz** [comment]
The code you showed is why I filed this issue in the first place. As you said on Mar 29:
> The current working directory is undefined for a Gradle build. You must not rely on it. 

Still, the code works in terminal on the Mac and in Intellij on Mac. I had to change it to the code above to make it also work in Netbeans.

**Comment by kelemen** [comment]
The code works in terminal only if you cd into the appropriate working directory first. That is not necessarily the case. You can run Gradle tasks from any directory on any project if you want to and it would break on command line as well. Also, the Gradle spec. explicitly states that the current working directory is undefined. That is, it will be something but you cannot rely on its value (if it works, you are just "lucky" but your script is still considered broken).
