### ISSUE TITLE
some built-in tasks definitions can't be adjusted: javadoc, test.single, etc

### ISSUE THREAD

**Issue by tcfurrer** [kelemen/netbeans-gradle-project#388]
The "built-in tasks" documentation says "Each of these commands can be freely adjusted in the project properties."  But this seems to only be true for a subset of them currently.  Can the plugin be enhanced to allow all existing built-in tasks to be adjusted?

To be more specific: In the project properties GUI editor "Built-in tasks" category, several of the documented built-in tasks don't appear in the drop-down, such as "Generate Javadoc" and "Test Single".  I tried manually editing .nb-gradle-properties to see if it was possible to adjust these task definitions, but this doesn't seem to take effect:

```
    <task>
      <display-name>javadoc</display-name>
      <non-blocking>yes</non-blocking>
      <task-names>
        <name must-exist="no">${project}:showJavadoc</name>
      </task-names>
      <task-args/>
      <task-jvm-args/>
    </task>
    <task>
      <display-name>test.single</display-name>
      <non-blocking>no</non-blocking>
      <task-names>
        <name must-exist="no">${project}:test</name>
      </task-names>
      <task-args>
        <arg>--tests '${selected-class}'</arg>
        <arg>-Ptest.suites=${test-suites}</arg>
      </task-args>
      <task-jvm-args/>
    </task>
```

**Comment by tcfurrer** [comment]
In case it matters:
I observed this using plugin version 1.4.3, Netbeans 8.2, both Windows and Linux.

**Comment by kelemen** [comment]
You can only see Java related tasks on Java projects (i.e., those applying the 'java' plugin), so - unless you have applied the 'java' plugin on the root - you can't see them if you select the project properties on the root project. This is somewhat awkward because projects within the same multi-project share the project properties (though I might consider adding the possiblitly to also adjust the properties per subproject).

**Comment by kelemen** [comment]
Also, manual changes made to the properties file are not tracked, so you would have to restart NB for that to take effect but I'm quite sure this feature works because I use it very regularly.

**Comment by tcfurrer** [comment]
Ok. I will try that, and report back here whether this entire issue becomes moot.

I don't actually want to apply the java plugin to my root project (if it can be avoided), but I'm OK with using the workaround you provided in [Issue 374](https://github.com/kelemen/netbeans-gradle-project/issues/374), which I hope will be equally applicable here.

**Comment by tcfurrer** [comment]
Ok, I did end up just applying java plugin to my root project all of the time.  That fixed things for "Generate Javadoc"... my adjusted definition which runs "showJavadoc" task works correctly now.

But my adjustments to "test.single" still aren't working.  Do you see anything wrong in the XML I showed here earlier?  Or is this an issue with the plugin?

Even with that test.single override (which does not include cleanTest, and which adds -Ptest.suites) present in .nb-gradle-properties, when I run the "Test File" operation, I'm still getting a default gradle cmdline like this:

gradle :<subproject>:cleanTest :<subproject>:test --tests <canonical.path.to.test.class>

**Comment by tcfurrer** [comment]
Closing, since it was just user error.

**Comment by kelemen** [comment]
You don't have to apply the java plugin but you have to open the project properties dialog on a java subproject (the properties are shared by all the projects in the build).

**Comment by tcfurrer** [comment]
Actually, no matter what I do, some built-in tasks never appear in the project properties dialog.  I'll file a new issue on that.

**Comment by tcfurrer** [comment]
Oops, nevermind, all the build-in tasks are there for me now.  I'm not sure what change I made that made this start working.  I have been making various changes in my gradle scripts, etc recently.  Anyway, no need for another issue now. :-)
