### ISSUE TITLE
Support for project spellcheck dictionary?

### ISSUE THREAD

**Issue by tcfurrer** [kelemen/netbeans-gradle-project#393]
With my older Ant project, we had a customized dictionary at nbproject/project.xml for Netbeans.  Is there any way to get back this functionality with the current netbeans gradle plugin?  Or would this require a plugin enhancement?  If so, is it feasible?

**Comment by tcfurrer** [comment]
Nevermind, I see that this actually does work and .nb-gradle-properties can store project dictionary already.  Awesome!

**Comment by kelemen** [comment]
Yes, this feature is (almost) completely independent of the plugin. The plugin just allows other parts of the IDE to store opaque properties.
