### ISSUE TITLE
Junit 5 Single Test method execution fails

### ISSUE THREAD

**Issue by qeepcologne** [kelemen/netbeans-gradle-project#399]
Szenario:
- Run Test class
- Test Results -> Right click -> Run Method again

I got from the output window:
`gradle :cleanTest :test --tests de.k2interactive.qeep.integrationtest.testcases.ChatRequestTest.testMethodXy()`

this is not working:

> No tests found for given includes: [de.k2interactive.qeep.integrationtest.testcases.ChatRequestTest.testMethodXy()](--tests filter)

i think correct is:

`gradle :cleanTest :test --tests de.k2interactive.qeep.integrationtest.testcases.ChatRequestTest.testMethodXy
`
(without the round brackets).

tested with gradle-4.10.2, NB9, i also tried this version:
http://plugins.netbeans.org/download/plugin/9800

**Comment by kelemen** [comment]
Do you have a sample project with which I can conveniently check this problem?

**Comment by kelemen** [comment]
I can reproduce it with this: https://github.com/junit-team/junit5-samples/tree/master/junit5-jupiter-starter-gradle. So I'll use this project for verification.

**Comment by kelemen** [comment]
I believe this issue should be fixed now in master. Can you verify it?

**Comment by qeepcologne** [comment]
thanks a lot, it's working now.
