### ISSUE TITLE
Generated Code (immutables.org) + NB 9.0 + gradle => "package exists in another module:"

### ISSUE THREAD

**Issue by andreaseberhoefer** [kelemen/netbeans-gradle-project#406]
Hi,
I would like to generate code with immutables.org via annotation-processing. Here is my build.gradle

```
apply plugin: 'java'
sourceCompatibility = 9

repositories {
    mavenCentral()
}

dependencies {    
    compileOnly 'org.immutables:value:2.7.3'
}

compileJava {
    options.compilerArgs += ["-s", "${buildDir}/apt"]
}

sourceSets {
    generated {
        java {
            srcDirs +=  "${buildDir}/apt"
            compileClasspath += sourceSets.main.compileClasspath
            compileClasspath += sourceSets.main.output
        }
    }
}
```
As you can set, I set the "-s" parameter for javac, so that the output for the annotation-processor is set to `build/apt` after that I set up a new SourceSet for the generated sources and can see the sources in netbeans. Until version 1.4.3 everything works good, but in version 2.0.1 I get the error "package exists in another module: immutable.gradle.test". 

Thanks for your help
Andreas

**Comment by tcfurrer** [comment]
That same error message is being discussed in #405
