### ISSUE TITLE
Dtest.debug deprecated

### ISSUE THREAD

**Issue by EmteeW** [kelemen/netbeans-gradle-project#411]
Gradle 5.0+ has deprecated this feature.  Use --debug-jvm instead.

see: https://github.com/gradle/gradle/issues/8156

**Comment by EmteeW** [comment]
(Gradle Support plugin 1.4.4 for Netbeans 8.2)

**Comment by EmteeW** [comment]
https://docs.gradle.org/5.0/userguide/upgrading_version_4.html#potential_breaking_changes

**Comment by kelemen** [comment]
Thanks. By the way, I recommend using the other debug mode (even though it is not the default for historical reasons).

**Comment by kelemen** [comment]
Sorry, forget about the recommendation, I just mixed some things up.

**Comment by kelemen** [comment]
I have removed my previous comments to avoid more confusion.

The recommended debug mode is: "Debugger listens for connections". This issue won't happen in this mode.

That said, I have fixed this issue in the *nb81* and *master* branches.
