### ISSUE TITLE
The output from Gradle 4.8+ isn't colorised

### ISSUE THREAD

**Issue by entonio** [kelemen/netbeans-gradle-project#416]
In my projects, if I specify Gradle 4.8 or higher in NB's Preferences as the version to use, the build output in the console is black where red is expected.

**Comment by kelemen** [comment]
stderr is red, while stdout is black. I'm guessing that whatever you are using to print in the logs changes behaviour with the Gradle version. That is, it prints to stderr in older version, while it prints to stdout now.

**Comment by entonio** [comment]
My setup is simply:
- NB 8.2 + java 8 and NB 10 + java 11
- this plugin
- any project, I've just created a blank one with a class with only `String a = new Object();`

And the colours in NB's `Output` pane, which I have with the standard settings, seem to be:
- red both for errors and the final error message up to Gradle 4.6
- black for errors and red for the final error message with Gradle 4.7
- black both for errors and the final error message with Gradle 4.8 and 5.1

Does nobody else have this issue?

**Comment by entonio** [comment]
(I mean standard javac errors, though it applies to all. Could gradle have started printing javac errors to stderr?)

**Comment by kelemen** [comment]
from the build script of course.

**Comment by entonio** [comment]
Adding `System.err.println("Test stderr")` in the main body of `build.gradle`:
- with gradle 4.6 it's printed red
- with gradle 4.7 it's printed black

**Comment by entonio** [comment]
Here is a sample project, one just the project, and the other with the files added by the process:
[Colours.zip](https://github.com/kelemen/netbeans-gradle-project/files/2775806/Colours.zip)
[Colours+.gradle.zip](https://github.com/kelemen/netbeans-gradle-project/files/2775807/Colours%2B.gradle.zip)

**Comment by kelemen** [comment]
It seems this is an [issue in Gradle](https://github.com/gradle/gradle/issues/7617) and was already fixed in Gradle 5.1. I have checked it, and it does indeed seems to be fixed in Gradle 5.1. See the logic in [bf5a22ec60f1091fd255c494b7804a6135da1853](https://github.com/gradle/gradle/pull/7693/commits/bf5a22ec60f1091fd255c494b7804a6135da1853).

**Comment by entonio** [comment]
You're correct. I apologise for having brought it up here. I had originally tested it with 5.1.1 and was convinced the problem was there as well. I must have become confused in the middle of all the NB + java + plugin + grade juggling.
I have reverted to `NB 8.2 on Java 8 + this 1.4.x using Java 8 + Gradle 4.6` because 
`NB 10 on Java 11 + this 2.0.x using Java 8 + Gradle 4.8+` seems to use a lot more CPU and be slower (I have to use Java 8 for compilation because the CheckerFramework only supports Java 8 as of yet).
