### ISSUE TITLE
generated code missing transitive dependencies

### ISSUE THREAD

**Issue by ratcashdev** [kelemen/netbeans-gradle-project#420]
While opening the https://github.com/real-logic/simple-binary-encoding project in Netbeans is successful, (plugin 2.0.2), the generated code in the directory `build/generated` is full of unknown imports, at least according to netbeans. the gradle build itself is actually successful.
It seems Netbeans is not picking up the transitive dependencies for the generated code.

**Comment by kelemen** [comment]
The problem with this project is that instead of putting the dependencies in the source set's classpath it configures the compiler task and the plugin assumes that the dependencies for the source set is what is in the compile classpath of the source set.

**Comment by ratcashdev** [comment]
Any idea how to fix this by editing the build.gradle?

**Comment by kelemen** [comment]
Instead of adjusting `compileGeneratedJava.classpath`, adjust`sourceSets.generated.compileClasspath` instead. Or even better to just do (and leave the classpath of the compiler task be):

```groovy
configurations {
    generatedCompile.extendsFrom compile
}
```

**Comment by ratcashdev** [comment]
Thank you! The first (adjust`sourceSets.generated.compileClasspath`) did not help. 
The second did though, however, now it says the MAIN does not have any dependencies, only 'generated'. But compiles OK, so may be just cosmetics.
