### ISSUE TITLE
Profiles not working when running 2.0.2 on Netbeans 11?

### ISSUE THREAD

**Issue by tcfurrer** [kelemen/netbeans-gradle-project#425]
I'm testing Netbeans 11 vc4 on Windows, and although I was able to get the plugin installed, and my projects loaded, for some reason the Profiles drop-down in the toolbar is disabled.  The Run:Set Project Configuration menu item is also disabled.

I had several pre-existing profiles in .nb-gradle/profiles that were very useful.  This is a very powerful feature.

This issue does not appear to be specific to any given project... it happens to me no matter what project I load.

For anyone unfamiliar with the "Profiles" feature I'm talking about here... it's the one documented at: 
https://github.com/kelemen/netbeans-gradle-project/wiki/Profiles

**Comment by tcfurrer** [comment]
Of the four new issues I filed today, this one is the most important.  It is a showstopper for my team trying to upgrade to Netbeans 11.

**Comment by kelemen** [comment]
This also seems very fishy. Let's find out first, if it is really not a conflict with the current built-in plugin.

**Comment by tcfurrer** [comment]
This issue went away when I uninstalled the "Gradle" and "Groovy and Gradle" plugins, leaving only the "Gradle Support" plugin installed. I didn't realize that it was necessary to actually uninstall those conflicting plugins. I thought the fact that they were "disabled" would be equivalent to them not being installed, and so I didn't think to try uninstalling them. Bad assumption on my part there.

**Comment by lucianomx** [comment]
I'm having this issue using Gradle plugin v1.0.1 with Netbeans 11. No matter what plugin is installed or uninstalled (versions below), the "project configurations" for Gradle is always "disabled". I have been using this feature with Netbeans 10 with no problems, but it seems to not work anymore in Netbeans 11 + Gradle.

**Plugin versions for Netbeans 11:**
Gradle 1.0.1 (Gradle category)
Gradle and Groovy 1.0.1 (Groovy category)
Groovy 1.36.1 (Groovy category)

**Comment by tcfurrer** [comment]
The "Gradle" plugin 1.0.1 is the new plugin included in Netbeans 11 by default.  It is completely separate from this plugin... you would need to file an issue in Netbeans Jira for problems with that one.

To use this older (but still working fine on Netbeans 11) plugin, you need to have "Groovy" and "Gradle Support" (version 2.0.2) plugins installed, and you must manually completely uninstall (not just disable) the "Gradle" and "Gradle and Groovy" plugins which are installed by default.
