### ISSUE TITLE
Running multiple selected test classes broken with Netbeans 11 and plugin 2.0.2

### ISSUE THREAD

**Issue by tcfurrer** [kelemen/netbeans-gradle-project#427]
I'm testing Netbeans 11 vc4 on Windows, and when I select multiple test classes and try to run them using the "Test Files" right-click menu item, only one of the test classes actually runs.  This is similar to issue #392, where a fix was already made for this same symptom.  Does a new fix need to be applied for Netbeans 11?

As always, if you aren't able to reproduce this easily, I could provide a tiny project to reproduce it on.

**Comment by tcfurrer** [comment]
Of the four new issues I filed today... this one is the second-most painful for my project.  We can maybe live without this capability for a while, but people will definitely miss it.

**Comment by kelemen** [comment]
Same as the other issues: I suspect conflict with the built-in support.

**Comment by tcfurrer** [comment]
This issue went away when I uninstalled the "Gradle" and "Groovy and Gradle" plugins, leaving only the "Gradle Support" plugin installed. I didn't realize that it was necessary to actually uninstall those conflicting plugins. I thought the fact that they were "disabled" would be equivalent to them not being installed, and so I didn't think to try uninstalling them. Bad assumption on my part there.
