### ISSUE TITLE
editor: build.gradle select in projects does not work

### ISSUE THREAD

**Issue by bernard01** [kelemen/netbeans-gradle-project#436]
How to reproduce:

- Open a build.gradle file in the editor
- In the Projects window, select a Java source file from another project
- Switch back to the build.gradle file in the editor
- [Ctrl+Shift+1] or [Right click] Select in Projects

Expected behavior:

In the project window, the build.gradle file should be selected so one can navigate the project

Actual behavior:

Nothing is selected / highlighted.

**Comment by kelemen** [comment]
Are you sure you are using this plugin? I have checked and the *build.gradle* gets selected as it should.

**Comment by bernard01** [comment]
Thanks for the quick response. Good question. I am using NetBeans  IDE 11.3 which includes gradle support via Modules installed: DukeScript Gradle Project Wizard, Gradle, Groovy and Gradle, Gradle Java EE, Groovy. What to do?

**Comment by kelemen** [comment]
Then you are not using this plugin, you should open an issue on NB issue page.

**Comment by bernard01** [comment]
Thanks for your advice.
