### ISSUE TITLE
Netbeans 12 Coverage report not reflecting ignored paths

### ISSUE THREAD

**Issue by LorenKeagle** [kelemen/netbeans-gradle-project#438]
I'm using Netbeans 12, with gradle wrapper 6.5.  I've managed to get the Jacoco report when executed from the CLI to not report dynamically generated classes by flagging them with a custom `@Generated` attribute.

However, in the IDE, the coverage report still displays all of these classes.  I assume that it's the gradle plugin that's responsible for generating the report, but please correct me if this issue belongs in another area of Netbeans.

**Comment by makiam** [comment]
@LorenKeagle latest NB uses other gradle plugin implementation by default. Probably good to check this and file this issue to Apache Netbeans bug tracker

**Comment by LorenKeagle** [comment]
I see.  Thank you for the response.  I'll try and figure out how to file issues over there.
