### ISSUE TITLE
Could not find Gradle Support plugin anymore on NetBean 8.2

### ISSUE THREAD

**Issue by mattwongca** [kelemen/netbeans-gradle-project#440]
Hello,

I am trying to reinstall my Java development environment on a new PC.
To get my old projects to work successfully, I installed the exact same version of Java and Netbeans IDE:

NetBeans IDE 8.2
Java JRE and JDK 1.8.0_212

However after doing that, it seems that I could not find the Gradle support anymore from the pluginPortal (It seems they are all gone and the new portal did not have Gradle support anymore)? Is there any other site that I could download this plugin anymore? Otherwise, I'll have to try to build the NBM from the source project. 

 Thanks,
   Mat

**Comment by kelemen** [comment]
Hi. Yes, all versions were uploaded to GitHub Releases from where you can download whichever version you want: https://github.com/kelemen/netbeans-gradle-project/releases

**Comment by mattwongca** [comment]
Thank Kelemen for your reply. It really helps and I'll try to see which plugin suit my system configuration. It has been a mess since they move the pluginportal in March.
