### ISSUE TITLE
Stop the daemon from NetBeans

### ISSUE THREAD

**Issue by imartinbe** [kelemen/netbeans-gradle-project#64]
Would it be possible to add in the plugin a menu item "Stop Gradle daemon" (and a toolbar button would be a +) to run the "gradle --stop" command as a workaround to the missing cancellation of specific task in Gradle API?

**Comment by KorvinGump** [comment]
So, can anyone give a simple example how i can stop gradle daemon in netbeans?

**Comment by kelemen** [comment]
This issue was closed because it needed cancellation which is now supported. Gradle provides no way to stop the daemon through its API. I personally just kill the daemon process.

**Comment by JustGregory** [comment]
Same here.
But as an additional, final thought, is it possible to hook into the IDE's closing handler, such that when closing NetBeans, any running daemons are also closed? I would presume it logical, if NetBeans must close, this must mean the end of the build session....
(not that the issue needs to be reopened for this suggestion, just curious if it's possible.)
