### ISSUE TITLE
"run focused test method" does not work for junit tests

### ISSUE THREAD

**Issue by darbie** [kelemen/netbeans-gradle-project#95]
When I select "run focused test method" with a gradle project it should run that one @Test method in the file. Instead it does nothing.

**Comment by dellgreen** [comment]
Don't know if there is a regression, but I am unable to run  "run focused test method"  in Netbeans 8.1 on Mac OS X 10.9.5 using gradle 2.9 or 2.10. Dialog pops up complaining about no tests passed in although stdout looks like it is as it should be. Have this problem with a number of different netbeans gradle projects.
Screen shots attached.

<img width="942" alt="screen shot 2016-01-09 at 10 05 18" src="https://cloud.githubusercontent.com/assets/12861109/12215538/b3759392-b6b8-11e5-9329-c2b98b2a8f07.png">


<img width="539" alt="screen shot 2016-01-09 at 09 59 33" src="https://cloud.githubusercontent.com/assets/12861109/12215530/67bc765a-b6b8-11e5-8762-32a4b0bb677b.png">

**Comment by kelemen** [comment]
What unit test framework are you using? Also, what is the value of `test.reports.junitXml.destination` in your project's build script?

**Comment by kelemen** [comment]
Also, given the output, it looks like you have no test code in the test source set. Where is the test code you want to execute?

**Comment by dellgreen** [comment]
apologies, stupidity on my behalf, my test configuration was incompatible with running focus methods tests. Have corrected the mistake and all now working correctly, thank you for your quick feedback

**Comment by kelemen** [comment]
No problem but how is it possible to disable single method test?

**Comment by dellgreen** [comment]
I had includes on test task set to include only classes matching a certain pattern which match my test suite class names, as I have some suites that are for automated testing and some test suites for offline testing. Not sure why clicking "Test File" in netbeans runs, but "run focused test method" doesn't. Clicking "Test Project" also failed which re-enforced what you mentioned that config was causing the problem.
